# Generated by Django 4.2.13 on 2026-09-30 10:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('COMPATIBLE', 'Compatible — can be applied together'), ('INCOMPATIBLE', 'Incompatible — mutually exclusive'), ('PREREQUISITE', 'Prerequisite — Scheme A must be obtained before Scheme B'), ('SEQUENTIAL', 'Sequential — Apply in specified sequence'), ('OVERLAPPING', 'Overlapping — Subsidies fund the same expenditure/cost head'), ('UNKNOWN', 'Unknown — Insufficient official statutory evidence')], default='UNKNOWN', max_length=30)),
                ('direction', models.CharField(choices=[('BIDIRECTIONAL', 'Bidirectional / Mutual'), ('A_TO_B', 'A to B (Scheme A -> Scheme B)'), ('B_TO_A', 'B to A (Scheme B -> Scheme A)')], default='BIDIRECTIONAL', max_length=20)),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='Structured conditions for compatibility/exclusion')),
                ('affected_cost_categories', models.JSONField(blank=True, default=list, help_text='Expenditure heads affected (e.g. plant_and_machinery, interest, collateral)')),
                ('evidence_ids', models.JSONField(blank=True, default=list, help_text='List of verified chunk/document IDs supporting this assertion')),
                ('policy_versions', models.JSONField(blank=True, default=dict, help_text='Policy versions under which relationship is verified')),
                ('last_verified', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(help_text='Plain-language explanation of relationship and tradeoffs')),
                ('source_evidence', models.TextField(blank=True, help_text='Quotation or summary of official clause')),
                ('confidence', models.FloatField(default=1.0)),
                ('is_demo_data', models.BooleanField(default=False, help_text='Flags synthetic demo relationship data clearly for auditing')),
                ('scheme_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_a', to='policies.scheme')),
                ('scheme_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_b', to='policies.scheme')),
            ],
            options={
                'db_table': 'scheme_relationships',
                'unique_together': {('scheme_a', 'scheme_b')},
            },
        ),
        migrations.CreateModel(
            name='RelationshipEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_title', models.CharField(max_length=255)),
                ('clause_reference', models.CharField(max_length=100)),
                ('clause_text', models.TextField()),
                ('official_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_records', to='relationships.schemerelationship')),
            ],
            options={
                'db_table': 'relationship_evidence',
            },
        ),
    ]
