# Generated by Django 4.2.13 on 2026-10-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemerelationship',
            name='relationship_type',
            field=models.CharField(choices=[('COMPATIBLE', 'Compatible - can be applied together'), ('INCOMPATIBLE', 'Incompatible - mutually exclusive'), ('PREREQUISITE', 'Prerequisite - Scheme A must be obtained before Scheme B'), ('SEQUENTIAL', 'Sequential - Apply in specified sequence'), ('OVERLAPPING', 'Overlapping - Subsidies fund the same expenditure/cost head'), ('UNKNOWN', 'Unknown - Insufficient official statutory evidence')], default='UNKNOWN', max_length=30),
        ),
    ]
