# Generated by Django 4.2.13 on 2026-09-30 10:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_profiles', '0001_initial'),
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('eligibility_rules', 'Eligibility Rules Change'), ('thresholds', 'Financial / Numeric Threshold Change'), ('dates', 'Effective Date / Deadline Change'), ('benefit_details', 'Benefit Amount / Percentage Change'), ('prerequisites', 'Prerequisite / Gateway Condition Change'), ('required_documents', 'Documentation Requirement Change'), ('application_route', 'Portal / Submission Route Change'), ('general', 'General Policy Amendment')], max_length=40)),
                ('materiality', models.CharField(choices=[('material', 'Material — Directly Impacts Eligibility / Benefit Quantum'), ('informational', 'Informational — Non-Scoring Procedural Clarification')], default='material', max_length=20)),
                ('change_summary', models.TextField(help_text='Human-readable explanation of change')),
                ('old_value', models.JSONField(blank=True, help_text='Prior policy / rule state', null=True)),
                ('new_value', models.JSONField(blank=True, help_text='New policy / rule state', null=True)),
                ('affected_rule_ids', models.JSONField(blank=True, default=list, help_text='Rule IDs impacted by this change')),
                ('effective_date', models.DateField(blank=True, help_text='Statutory effective date of the amendment', null=True)),
                ('evidence_source', models.TextField(help_text='Official Gazette citation, clause, page, or document reference')),
                ('confidence_of_extraction', models.FloatField(default=1.0, help_text='Extraction confidence score (0.0 to 1.0)')),
                ('requires_human_review', models.BooleanField(default=False, help_text='If True, change must be approved before triggering downstream profile re-evaluations')),
                ('review_status', models.CharField(choices=[('pending_review', 'Pending Curated Human Review'), ('approved_active', 'Approved & Active in Rule Engine'), ('rejected', 'Rejected by Curator')], default='approved_active', max_length=30)),
                ('reviewed_by', models.CharField(blank=True, help_text='Username or email of reviewing curator', max_length=150)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False, help_text='Whether downstream impact mapping has completed')),
                ('source_notification', models.CharField(blank=True, max_length=255)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_changes', to='policies.scheme')),
            ],
            options={
                'db_table': 'policy_changes',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='ImpactEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('impact_type', models.CharField(max_length=50)),
                ('status_transition', models.CharField(blank=True, help_text="e.g. 'DOES_NOT_MATCH -> POTENTIAL_MATCH'", max_length=80)),
                ('previous_status', models.CharField(blank=True, max_length=40)),
                ('new_status', models.CharField(blank=True, max_length=40)),
                ('previous_benefit_lakhs', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('new_benefit_lakhs', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('delta_benefit_lakhs', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('evidence_ids', models.JSONField(blank=True, default=list, help_text='Official statutory chunk IDs')),
                ('official_citation', models.TextField(blank=True, help_text='Statutory clause reference or quotation')),
                ('user_facing_explanation', models.TextField(help_text='Plain-language explanation grounded in evidence with zero false guarantees')),
                ('impact_summary', models.TextField(blank=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('re_evaluated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_impacts', to='business_profiles.businessprofile')),
                ('policy_change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impacts', to='policy_monitoring.policychange')),
            ],
            options={
                'db_table': 'impact_evaluations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='policychange',
            index=models.Index(fields=['scheme', 'review_status'], name='policy_chan_scheme__c86ce0_idx'),
        ),
        migrations.AddIndex(
            model_name='policychange',
            index=models.Index(fields=['change_type', 'materiality'], name='policy_chan_change__0ccb04_idx'),
        ),
        migrations.AddIndex(
            model_name='policychange',
            index=models.Index(fields=['detected_at'], name='policy_chan_detecte_0b1d1b_idx'),
        ),
        migrations.AddIndex(
            model_name='impactevaluation',
            index=models.Index(fields=['business_profile', 'impact_type'], name='impact_eval_busines_fe8df0_idx'),
        ),
        migrations.AddIndex(
            model_name='impactevaluation',
            index=models.Index(fields=['policy_change', 're_evaluated_at'], name='impact_eval_policy__f11666_idx'),
        ),
    ]
