# Generated by Django 4.2.13 on 2026-10-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policychange',
            name='materiality',
            field=models.CharField(choices=[('material', 'Material - Directly Impacts Eligibility / Benefit Quantum'), ('informational', 'Informational - Non-Scoring Procedural Clarification')], default='material', max_length=20),
        ),
    ]
