# Generated by Django 4.2.13 on 2026-09-30 10:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_profiles', '0001_initial'),
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_status', models.CharField(choices=[('MATCH', 'Match'), ('POTENTIAL_MATCH', 'Potential Match'), ('DOES_NOT_MATCH', 'Does Not Match'), ('UNKNOWN', 'Unknown'), ('REQUIRES_OFFICIAL_VERIFICATION', 'Requires Official Verification')], max_length=40)),
                ('score', models.FloatField(default=0.0)),
                ('condition_results', models.JSONField(default=list)),
                ('mandatory_failures', models.JSONField(default=list)),
                ('missing_info', models.JSONField(default=list)),
                ('summary_explanation', models.TextField(blank=True)),
                ('relevance_score', models.FloatField(default=0.0, help_text='How relevant is this scheme to the stated goal')),
                ('relevance_explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='business_profiles.businessprofile')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='business_profiles.businessgoal')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='policies.scheme')),
            ],
            options={
                'db_table': 'eligibility_evaluations',
                'ordering': ['-score', '-relevance_score'],
                'unique_together': {('goal', 'scheme')},
            },
        ),
        migrations.CreateModel(
            name='ConditionEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_name', models.CharField(max_length=200)),
                ('rule_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('UNKNOWN', 'Unknown')], max_length=20)),
                ('evaluated_value', models.JSONField(blank=True, null=True)),
                ('expected_value', models.JSONField(blank=True, null=True)),
                ('importance', models.CharField(default='mandatory', max_length=20)),
                ('source_clause', models.TextField(blank=True)),
                ('display_label', models.CharField(blank=True, max_length=255)),
                ('explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_records', to='eligibility.eligibilityevaluation')),
            ],
            options={
                'db_table': 'condition_evaluations',
            },
        ),
        migrations.CreateModel(
            name='Blocker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blocker_category', models.CharField(choices=[('mandatory_failure', 'Mandatory Condition Failed'), ('missing_fact', 'Missing Business Profile Fact'), ('jurisdiction_exclusion', 'Taluka or State Excluded'), ('quota_exhausted', 'Annual Scheme Budget / Quota Exhausted')], max_length=40)),
                ('description', models.TextField()),
                ('resolution_path', models.TextField(blank=True)),
                ('is_resolvable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condition_evaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eligibility.conditionevaluation')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockers', to='eligibility.eligibilityevaluation')),
            ],
            options={
                'db_table': 'evaluation_blockers',
            },
        ),
        migrations.AddIndex(
            model_name='conditionevaluation',
            index=models.Index(fields=['evaluation', 'status'], name='condition_e_evaluat_080c86_idx'),
        ),
    ]
