# Generated by Django 4.2.13 on 2026-09-30 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessFact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fact_key', models.CharField(help_text='e.g., msme_category, annual_turnover', max_length=100)),
                ('fact_value', models.JSONField()),
                ('fact_type', models.CharField(choices=[('self_declared', 'Self Declared'), ('document_verified', 'Document Verified'), ('official_registry', 'Official Registry'), ('system_derived', 'System Derived')], default='self_declared', max_length=30)),
                ('confidence', models.FloatField(default=1.0, help_text='0.0 to 1.0')),
                ('source_description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'business_facts',
            },
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255)),
                ('udyam_registration_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('pan', models.CharField(blank=True, max_length=10, null=True)),
                ('msme_category', models.CharField(choices=[('micro', 'Micro'), ('small', 'Small'), ('medium', 'Medium')], max_length=20)),
                ('entity_type', models.CharField(choices=[('proprietorship', 'Proprietorship'), ('partnership', 'Partnership'), ('llp', 'Limited Liability Partnership'), ('pvt_ltd', 'Private Limited Company'), ('public_ltd', 'Public Limited Company'), ('cooperative', 'Cooperative'), ('opc', 'One Person Company')], max_length=30)),
                ('nic_code', models.CharField(blank=True, help_text='NIC 2008 activity code', max_length=10, null=True)),
                ('industry_sector', models.CharField(blank=True, max_length=100)),
                ('industry_subsector', models.CharField(blank=True, max_length=100)),
                ('is_manufacturing', models.BooleanField(default=True)),
                ('is_service', models.BooleanField(default=False)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=6)),
                ('is_rural', models.BooleanField(default=False)),
                ('is_aspirational_district', models.BooleanField(default=False)),
                ('investment_in_plant_machinery_lakhs', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('annual_turnover_lakhs', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('owner_gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('owner_caste', models.CharField(blank=True, choices=[('general', 'General'), ('obc', 'OBC'), ('sc', 'SC'), ('st', 'ST')], max_length=10)),
                ('is_sc_st_owned', models.BooleanField(default=False)),
                ('is_women_owned', models.BooleanField(default=False)),
                ('is_minority_owned', models.BooleanField(default=False)),
                ('is_differently_abled_owner', models.BooleanField(default=False)),
                ('years_in_operation', models.IntegerField(blank=True, null=True)),
                ('total_employees', models.IntegerField(blank=True, null=True)),
                ('has_bank_account', models.BooleanField(default=True)),
                ('has_existing_loan', models.BooleanField(default=False)),
                ('existing_loan_bank', models.CharField(blank=True, max_length=100)),
                ('is_npa', models.BooleanField(default=False)),
                ('credit_score', models.IntegerField(blank=True, null=True)),
                ('has_iso_certification', models.BooleanField(default=False)),
                ('has_bis_certification', models.BooleanField(default=False)),
                ('has_gem_registration', models.BooleanField(default=False)),
                ('has_export_license', models.BooleanField(default=False)),
                ('has_technology_upgrade_plan', models.BooleanField(default=False)),
                ('uses_digital_payments', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'business_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileChangeHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('is_material', models.BooleanField(default=False, help_text='True if this change materially affects scheme eligibility criteria (e.g. turnover, investment, state, category)')),
                ('change_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_history', to='business_profiles.businessprofile')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile_change_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FactEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('self_declared', 'Self Declared'), ('document_supported', 'Document Supported'), ('official_registry', 'Official Registry Verified'), ('ca_certified', 'Chartered Accountant Certified')], default='self_declared', max_length=40)),
                ('document_reference', models.CharField(blank=True, max_length=255)),
                ('verification_notes', models.TextField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('confidence_score', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='business_profiles.businessfact')),
            ],
            options={
                'db_table': 'fact_evidence',
            },
        ),
        migrations.CreateModel(
            name='ConsistencyCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fact_key', models.CharField(max_length=100)),
                ('self_declared_value', models.JSONField()),
                ('verified_document_value', models.JSONField()),
                ('has_discrepancy', models.BooleanField(default=False)),
                ('discrepancy_explanation', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consistency_checks', to='business_profiles.businessprofile')),
            ],
            options={
                'db_table': 'consistency_checks',
            },
        ),
        migrations.CreateModel(
            name='BusinessGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_goal_text', models.TextField()),
                ('parsed_objective', models.TextField(blank=True)),
                ('parsed_project_type', models.CharField(blank=True, max_length=100)),
                ('parsed_investment_amount_lakhs', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('parsed_support_categories', models.JSONField(default=list)),
                ('parsed_industry_hints', models.JSONField(default=list)),
                ('parsed_missing_info', models.JSONField(default=list, help_text='High-impact missing profile facts')),
                ('status', models.CharField(choices=[('pending', 'Pending Analysis'), ('analyzing', 'Analyzing'), ('ready', 'Strategy Ready'), ('error', 'Analysis Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='business_profiles.businessprofile')),
            ],
            options={
                'db_table': 'business_goals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='businessfact',
            name='business_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='business_profiles.businessprofile'),
        ),
        migrations.CreateModel(
            name='ProfileSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_version', models.IntegerField(default=1)),
                ('snapshot_data', models.JSONField(help_text='Complete frozen dictionary of business profile fields and provenances')),
                ('trigger_reason', models.CharField(default='manual_update', help_text='Reason snapshot was created: evaluation_run, material_field_change, pre_update, manual_snapshot', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='business_profiles.businessprofile')),
            ],
            options={
                'db_table': 'profile_snapshots',
                'ordering': ['-snapshot_version', '-created_at'],
                'unique_together': {('business_profile', 'snapshot_version')},
            },
        ),
        migrations.CreateModel(
            name='ProfileFieldProvenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(help_text='e.g. annual_turnover_lakhs, udyam_registration_number, state', max_length=100)),
                ('source_type', models.CharField(choices=[('self_declared', 'Self Declared'), ('document_supported', 'Document Supported'), ('official_registry', 'Official Registry Verified'), ('ca_certified', 'Chartered Accountant Certified')], default='self_declared', max_length=40)),
                ('document_reference', models.CharField(blank=True, help_text='e.g. UDYAM-REG-01-0012, GST-GSTR3B-2025-Q3', max_length=255, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_provenances', to='business_profiles.businessprofile')),
            ],
            options={
                'db_table': 'profile_field_provenances',
                'unique_together': {('business_profile', 'field_name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='businessfact',
            unique_together={('business_profile', 'fact_key')},
        ),
    ]
