# Generated by Django 4.2.13 on 2026-09-30 10:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pgvector.django.vector
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_title', models.CharField(max_length=300)),
                ('document_url', models.URLField(blank=True)),
                ('document_type', models.CharField(blank=True, max_length=50)),
                ('ministry', models.CharField(blank=True, max_length=200)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('clause_reference', models.CharField(blank=True, max_length=100)),
                ('chunk_text', models.TextField()),
                ('chunk_index', models.IntegerField(default=0)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'document_chunks',
                'ordering': ['document_title', 'chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='PolicyVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_tag', models.CharField(help_text="Canonical semantic or statutory version tag, e.g. 'v2024.1', 'v2025.1'", max_length=50)),
                ('version_number', models.IntegerField(help_text='Sequential version integer (1, 2, 3...)')),
                ('effective_from', models.DateField(help_text='Date on which this policy version came into legal force')),
                ('effective_until', models.DateField(blank=True, help_text='Date on which this policy version was superseded or expired (null = current active)', null=True)),
                ('source_authority', models.CharField(help_text="e.g. 'Industries Commissionerate, Govt of Gujarat'", max_length=255)),
                ('source_document', models.CharField(help_text='Official resolution or Gazette title', max_length=300)),
                ('document_checksum', models.CharField(help_text='SHA-256 cryptographic hash of official Gazette PDF / notification', max_length=64)),
                ('clause_or_page', models.CharField(help_text="e.g. 'Clauses 4.1 to 4.8, pp. 12-16'", max_length=150)),
                ('last_verified', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of statutory verification')),
                ('is_active', models.BooleanField(default=False, help_text='Exactly one version may be active per scheme at any given time')),
                ('is_immutable', models.BooleanField(default=True, help_text='Once published, this historical version cannot be modified in-place')),
                ('rules_snapshot', models.JSONField(default=list, help_text='Complete frozen snapshot of deterministic rules and thresholds at this version')),
                ('benefits_snapshot', models.JSONField(blank=True, default=dict, help_text='Frozen snapshot of benefit ceilings, percentages, and subsidies')),
                ('change_summary', models.TextField(help_text='Audit explanation of additions, removals, and changed thresholds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'policy_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheme_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('short_name', models.CharField(blank=True, max_length=100)),
                ('ministry_department', models.CharField(max_length=200)),
                ('implementing_agency', models.CharField(blank=True, max_length=200)),
                ('level', models.CharField(choices=[('central', 'Central Government'), ('state', 'State Government'), ('state_gujarat', 'Gujarat State')], max_length=30)),
                ('support_type', models.CharField(choices=[('capital_subsidy', 'Capital Subsidy'), ('interest_subvention', 'Interest Subvention'), ('credit_guarantee', 'Credit Guarantee'), ('collateral_free_loan', 'Collateral Free Loan'), ('technology_grant', 'Technology Grant'), ('export_incentive', 'Export Incentive'), ('marketing_support', 'Marketing Support'), ('skill_training', 'Skill Training'), ('infrastructure', 'Infrastructure Support'), ('quality_certification', 'Quality Certification'), ('digitalization', 'Digitalization Support'), ('equity', 'Equity/VC Support'), ('raw_material', 'Raw Material Support'), ('multiple', 'Multiple Benefits')], max_length=30)),
                ('target_sectors', models.JSONField(default=list, help_text='NIC codes or sector names')),
                ('target_msme_categories', models.JSONField(default=list, help_text='["micro","small","medium"]')),
                ('target_states', models.JSONField(default=list, help_text='Empty means all states')),
                ('max_benefit_amount_lakhs', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('benefit_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('benefit_description', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('upcoming', 'Upcoming')], default='active', max_length=20)),
                ('launch_date', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('official_portal_url', models.URLField(blank=True)),
                ('official_document_url', models.URLField(blank=True)),
                ('gazette_notification', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('eligibility_summary', models.TextField(blank=True)),
                ('application_process', models.TextField(blank=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('search_text', models.TextField(blank=True, help_text='Combined text for full-text search')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'schemes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SourceMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_title', models.CharField(max_length=300)),
                ('issuing_ministry', models.CharField(max_length=255)),
                ('document_type', models.CharField(max_length=50)),
                ('notification_number', models.CharField(blank=True, max_length=150)),
                ('official_url', models.URLField()),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('last_verified_date', models.DateField(auto_now=True)),
                ('sha256_checksum', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'source_metadata',
            },
        ),
        migrations.CreateModel(
            name='SchemeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('change_summary', models.TextField()),
                ('changed_fields', models.JSONField(default=dict)),
                ('effective_date', models.DateField()),
                ('source_document', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='policies.scheme')),
            ],
            options={
                'db_table': 'scheme_versions',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='SchemeRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_name', models.CharField(max_length=200)),
                ('field_path', models.CharField(help_text='BusinessProfile field to evaluate', max_length=100)),
                ('operator', models.CharField(choices=[('eq', 'Equals'), ('ne', 'Not Equals'), ('gt', 'Greater Than'), ('gte', 'Greater Than or Equal'), ('lt', 'Less Than'), ('lte', 'Less Than or Equal'), ('in', 'In List'), ('not_in', 'Not In List'), ('contains', 'Contains'), ('bool_true', 'Must Be True'), ('bool_false', 'Must Be False'), ('not_null', 'Must Be Present'), ('range', 'Within Range')], max_length=20)),
                ('expected_value', models.JSONField(blank=True, null=True)),
                ('importance', models.CharField(choices=[('mandatory', 'Mandatory — disqualifies if fails'), ('preferred', 'Preferred — reduces score if fails'), ('bonus', 'Bonus — improves score if passes'), ('info', 'Informational — no scoring impact')], default='mandatory', max_length=20)),
                ('source_clause', models.TextField(blank=True, help_text='Exact clause from official document')),
                ('source_document', models.CharField(blank=True, max_length=255)),
                ('source_page', models.CharField(blank=True, max_length=20)),
                ('display_label', models.CharField(blank=True, max_length=200)),
                ('failure_message', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='policies.scheme')),
            ],
            options={
                'db_table': 'scheme_rules',
                'ordering': ['order', 'importance'],
            },
        ),
        migrations.CreateModel(
            name='SchemeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('local_file', models.FileField(blank=True, null=True, upload_to='official_policies/%Y/')),
                ('total_pages', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_documents', to='policies.scheme')),
                ('source_metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.sourcemetadata')),
            ],
            options={
                'db_table': 'scheme_documents',
            },
        ),
        migrations.CreateModel(
            name='SchemeBenefit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('benefit_name', models.CharField(max_length=200)),
                ('benefit_type', models.CharField(max_length=50)),
                ('amount_or_percentage', models.CharField(max_length=100)),
                ('cap_amount_lakhs', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('conditions', models.TextField(blank=True)),
                ('source_clause', models.TextField(blank=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='policies.scheme')),
            ],
            options={
                'db_table': 'scheme_benefits',
            },
        ),
        migrations.AddIndex(
            model_name='scheme',
            index=models.Index(fields=['status', 'level'], name='schemes_status_76e22f_idx'),
        ),
        migrations.AddIndex(
            model_name='scheme',
            index=models.Index(fields=['status', 'support_type'], name='schemes_status_e9ebe7_idx'),
        ),
        migrations.AddIndex(
            model_name='scheme',
            index=models.Index(fields=['scheme_code'], name='schemes_scheme__bcaf00_idx'),
        ),
        migrations.AddIndex(
            model_name='scheme',
            index=models.Index(fields=['created_at'], name='schemes_created_03523c_idx'),
        ),
        migrations.AddField(
            model_name='policyversion',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_versions', to='policies.scheme'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='policies.scheme'),
        ),
        migrations.AlterUniqueTogether(
            name='schemeversion',
            unique_together={('scheme', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='schemerule',
            index=models.Index(fields=['scheme', 'is_active', 'order'], name='scheme_rule_scheme__7165b2_idx'),
        ),
        migrations.AddIndex(
            model_name='schemerule',
            index=models.Index(fields=['field_path', 'is_active'], name='scheme_rule_field_p_ab20ae_idx'),
        ),
        migrations.AddIndex(
            model_name='schemerule',
            index=models.Index(fields=['importance'], name='scheme_rule_importa_5b3ad1_idx'),
        ),
        migrations.AddIndex(
            model_name='policyversion',
            index=models.Index(fields=['scheme', 'is_active'], name='policy_vers_scheme__ec445b_idx'),
        ),
        migrations.AddIndex(
            model_name='policyversion',
            index=models.Index(fields=['effective_from', 'effective_until'], name='policy_vers_effecti_8fe030_idx'),
        ),
        migrations.AddIndex(
            model_name='policyversion',
            index=models.Index(fields=['document_checksum'], name='policy_vers_documen_bc21ed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='policyversion',
            unique_together={('scheme', 'version_tag'), ('scheme', 'version_number')},
        ),
    ]
