# Generated by Django 4.2.13 on 2026-10-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='division',
            field=models.CharField(blank=True, default='', help_text='Departmental division, e.g. MSME, Gujarat State, Agriculture, Social Welfare', max_length=150),
        ),
        migrations.AddField(
            model_name='scheme',
            name='pdf_filename',
            field=models.CharField(blank=True, default='', help_text='Source PDF document filename', max_length=255),
        ),
        migrations.AlterField(
            model_name='schemerule',
            name='importance',
            field=models.CharField(choices=[('mandatory', 'Mandatory - disqualifies if fails'), ('preferred', 'Preferred - reduces score if fails'), ('bonus', 'Bonus - improves score if passes'), ('info', 'Informational - no scoring impact')], default='mandatory', max_length=20),
        ),
    ]
