# Generated by Django 4.2.13 on 2026-09-30 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSecurityProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('msme_user', 'MSME Business Owner / Representative'), ('policy_analyst', 'Government Policy Analyst'), ('compliance_officer', 'Compliance Officer'), ('system_admin', 'System Administrator')], default='msme_user', max_length=30)),
                ('failed_login_attempts', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('password_changed_at', models.DateTimeField(auto_now_add=True)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('mfa_secret', models.CharField(blank=True, help_text='TOTP Secret Key (AES encrypted in prod)', max_length=64)),
                ('privacy_consent_at', models.DateTimeField(blank=True, null=True)),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Security Profile',
                'verbose_name_plural': 'User Security Profiles',
                'db_table': 'auth_user_security_profiles',
            },
        ),
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor_username', models.CharField(blank=True, help_text='Preserved username in case user is deleted', max_length=150)),
                ('action', models.CharField(choices=[('login_success', 'User Login Successful'), ('login_failed', 'Failed Login Attempt'), ('account_locked', 'Account Locked due to Brute-Force'), ('permission_denied', 'Unauthorized Object Access Denied'), ('profile_created', 'Business Profile Created'), ('profile_updated', 'Business Profile Updated'), ('document_uploaded', 'Document Uploaded'), ('document_deleted', 'Document Deleted'), ('strategy_generated', 'Strategy Plan Generated'), ('policy_change_approved', 'Policy Change Approved by Admin'), ('security_setting_changed', 'Security Configuration Changed')], db_index=True, max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('resource_type', models.CharField(blank=True, help_text='e.g. BusinessProfile, BusinessDocument', max_length=100)),
                ('resource_id', models.CharField(blank=True, help_text='Target entity UUID', max_length=100)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('DENIED', 'Denied'), ('FAILURE', 'Failure')], default='SUCCESS', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_security_audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action', 'timestamp'], name='auth_securi_action_03d023_idx'), models.Index(fields=['user', 'timestamp'], name='auth_securi_user_id_fdbc2a_idx'), models.Index(fields=['resource_type', 'resource_id'], name='auth_securi_resourc_6f209d_idx')],
            },
        ),
    ]
