import React, { useState } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import {
  Box,
  Typography,
  Button,
  Stack,
  Card,
  CardContent,
  Chip,
  Grid,
  Divider,
  Paper,
  Tabs,
  Tab,
  Checkbox,
  LinearProgress,
  Alert,
  Tooltip,
  CircularProgress,
  alpha,
} from '@mui/material'
import ArrowBackIcon from '@mui/icons-material/ArrowBack'
import CalendarTodayOutlinedIcon from '@mui/icons-material/CalendarTodayOutlined'
import VerifiedUserIcon from '@mui/icons-material/VerifiedUser'
import OpenInNewIcon from '@mui/icons-material/OpenInNew'
import StarIcon from '@mui/icons-material/Star'
import CheckCircleIcon from '@mui/icons-material/CheckCircle'
import AssignmentTurnedInIcon from '@mui/icons-material/AssignmentTurnedIn'
import AccountBalanceIcon from '@mui/icons-material/AccountBalance'
import SecurityIcon from '@mui/icons-material/Security'
import FileDownloadOutlinedIcon from '@mui/icons-material/FileDownloadOutlined'
import InfoOutlinedIcon from '@mui/icons-material/InfoOutlined'
import { tokens } from '../theme/tokens'
import { useScheme } from '../api/hooks'
import { toast } from 'sonner'

export const SchemeDetailPage: React.FC = () => {
  const { id } = useParams<{ id: string }>()
  const navigate = useNavigate()
  const { data: scheme, isLoading, error } = useScheme(id)
  
  const [activeTab, setActiveTab] = useState(0)
  const [checkedDocs, setCheckedDocs] = useState<Record<string, boolean>>({})

  const toggleDoc = (docId: string) => {
    setCheckedDocs((prev) => {
      const next = { ...prev, [docId]: !prev[docId] }
      return next
    })
  }

  const handleExportChecklist = () => {
    if (!scheme) return
    const docs = scheme.required_documents || []
    const checklistText = `UDYAMNITI - STATUTORY SCHEME DOCUMENT CHECKLIST\n` +
      `Scheme: ${scheme.name} (${scheme.scheme_code})\n` +
      `Official Reference: ${scheme.gazette_notification || 'Official Gazette'}\n` +
      `Application Deadline: ${scheme.deadline || 'March 31, 2027'}\n` +
      `------------------------------------------------------------------\n` +
      docs.map((d: any, idx: number) => `[${checkedDocs[d.id] ? 'X' : ' '}] ${idx + 1}. ${d.name}\n    Category: ${d.category} | ${d.desc}`).join('\n\n') +
      `\n------------------------------------------------------------------\n` +
      `Generated by UdyamNiti SaaS Platform on ${new Date().toLocaleDateString()}`

    const blob = new Blob([checklistText], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `${scheme.scheme_code}_document_checklist.txt`
    link.click()
    URL.revokeObjectURL(url)
    toast.success('Document checklist downloaded!')
  }

  if (isLoading) {
    return (
      <Box sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', minHeight: '60vh' }}>
        <CircularProgress size={40} sx={{ color: tokens.color.violet[500] }} />
      </Box>
    )
  }

  if (error || !scheme) {
    return (
      <Box sx={{ maxWidth: 800, mx: 'auto', px: 3, py: 6, textAlign: 'center' }}>
        <Typography variant="h6" sx={{ color: tokens.color.slate[100] }}>
          Scheme details could not be retrieved.
        </Typography>
        <Button
          startIcon={<ArrowBackIcon />}
          onClick={() => navigate('/dashboard')}
          sx={{ mt: 2, color: tokens.color.violet[400] }}
        >
          Return to Dashboard
        </Button>
      </Box>
    )
  }

  const requiredDocs = scheme.required_documents || []
  const checkedCount = requiredDocs.filter((d: any) => checkedDocs[d.id]).length
  const progressPercent = requiredDocs.length > 0 ? Math.round((checkedCount / requiredDocs.length) * 100) : 0

  return (
    <Box sx={{ maxWidth: 1240, mx: 'auto', px: { xs: 2, sm: 3, md: 4 }, py: 3.5 }}>
      {/* Back button & Breadcrumb */}
      <Stack direction="row" alignItems="center" spacing={1} sx={{ mb: 2.5 }}>
        <Button
          size="small"
          startIcon={<ArrowBackIcon />}
          onClick={() => navigate('/dashboard')}
          sx={{
            color: tokens.color.slate[400],
            textTransform: 'none',
            fontSize: '0.82rem',
            '&:hover': { color: tokens.color.slate[100] },
          }}
        >
          Back to Schemes Dashboard
        </Button>
        <Typography variant="caption" sx={{ color: tokens.color.slate[600] }}>
          /
        </Typography>
        <Typography variant="caption" sx={{ color: tokens.color.slate[300], fontWeight: 600 }}>
          {scheme.short_name || scheme.scheme_code}
        </Typography>
      </Stack>

      {/* Top Scheme Hero Card */}
      <Card
        sx={{
          mb: 3.5,
          borderRadius: '14px',
          bgcolor: tokens.color.surface.card,
          border: `1px solid ${scheme.is_best_deal ? alpha(tokens.color.amber[500], 0.4) : tokens.color.border.subtle}`,
          boxShadow: '0 8px 30px rgba(0, 0, 0, 0.32)',
          overflow: 'hidden',
          position: 'relative',
        }}
      >
        {scheme.is_best_deal && (
          <Box
            sx={{
              position: 'absolute',
              top: 0,
              left: 0,
              right: 0,
              height: 3,
              background: 'linear-gradient(90deg, #F59E0B 0%, #6366F1 100%)',
            }}
          />
        )}
        <CardContent sx={{ p: { xs: 2.5, sm: 3.5 } }}>
          <Stack direction={{ xs: 'column', md: 'row' }} justifyContent="space-between" spacing={3}>
            <Box sx={{ flex: 1 }}>
              {/* Badges */}
              <Stack direction="row" spacing={1} alignItems="center" flexWrap="wrap" sx={{ mb: 1.5, gap: 0.5 }}>
                {scheme.is_best_deal && (
                  <Chip
                    icon={<StarIcon sx={{ fontSize: '14px !important', color: '#0F172A !important' }} />}
                    label="TOP RECOMMENDED DEAL"
                    size="small"
                    sx={{
                      bgcolor: tokens.color.amber[400],
                      color: '#0F172A',
                      fontWeight: 800,
                      fontSize: '0.7rem',
                      height: 24,
                    }}
                  />
                )}
                <Chip
                  label={scheme.scheme_code}
                  size="small"
                  sx={{
                    bgcolor: alpha(tokens.color.slate[700], 0.5),
                    color: tokens.color.slate[300],
                    fontSize: '0.72rem',
                    height: 24,
                    fontWeight: 700,
                  }}
                />
                <Chip
                  label={scheme.level === 'state_gujarat' ? 'Gujarat State Government' : 'Central Government'}
                  size="small"
                  sx={{
                    bgcolor: scheme.level === 'state_gujarat' ? alpha(tokens.color.emerald[500], 0.15) : alpha(tokens.color.blue[500], 0.15),
                    color: scheme.level === 'state_gujarat' ? tokens.color.emerald[300] : tokens.color.blue[300],
                    fontSize: '0.72rem',
                    height: 24,
                    fontWeight: 600,
                  }}
                />
                <Chip
                  label={scheme.status === 'active' ? 'Active / Open' : scheme.status}
                  size="small"
                  sx={{
                    bgcolor: alpha(tokens.color.emerald[500], 0.12),
                    color: tokens.color.emerald[400],
                    fontSize: '0.72rem',
                    height: 24,
                  }}
                />
              </Stack>

              {/* Title */}
              <Typography
                variant="h5"
                component="h1"
                sx={{
                  fontWeight: 800,
                  color: tokens.color.slate[50],
                  fontSize: { xs: '1.25rem', md: '1.55rem' },
                  lineHeight: 1.3,
                  mb: 1,
                }}
              >
                {scheme.name}
              </Typography>

              {/* Ministry & Gazette */}
              <Typography variant="body2" sx={{ color: tokens.color.slate[300], fontSize: '0.86rem', mb: 0.5 }}>
                <strong>Ministry / Department:</strong> {scheme.ministry}
              </Typography>
              {scheme.implementing_agency && (
                <Typography variant="body2" sx={{ color: tokens.color.slate[400], fontSize: '0.82rem', mb: 0.5 }}>
                  <strong>Nodal Agency:</strong> {scheme.implementing_agency}
                </Typography>
              )}
              {scheme.gazette_notification && (
                <Typography variant="caption" sx={{ color: tokens.color.violet[300], display: 'block', fontSize: '0.78rem', mt: 0.5 }}>
                  <strong>Official Reference:</strong> {scheme.gazette_notification}
                </Typography>
              )}
            </Box>

            {/* Quick Actions Column */}
            <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1.5, minWidth: { md: 240 } }}>
              {scheme.official_portal_url && (
                <Button
                  variant="contained"
                  component="a"
                  href={scheme.official_portal_url}
                  target="_blank"
                  rel="noreferrer"
                  endIcon={<OpenInNewIcon sx={{ fontSize: 16 }} />}
                  sx={{
                    bgcolor: tokens.color.violet[500],
                    color: '#FFFFFF',
                    fontWeight: 700,
                    fontSize: '0.84rem',
                    py: 1,
                    borderRadius: '8px',
                    textTransform: 'none',
                    '&:hover': { bgcolor: tokens.color.violet[600] },
                  }}
                >
                  Apply on Official Portal
                </Button>
              )}

              <Button
                variant="outlined"
                startIcon={<FileDownloadOutlinedIcon />}
                onClick={handleExportChecklist}
                sx={{
                  borderColor: tokens.color.border.subtle,
                  color: tokens.color.slate[200],
                  fontWeight: 600,
                  fontSize: '0.82rem',
                  py: 0.85,
                  borderRadius: '8px',
                  textTransform: 'none',
                  '&:hover': {
                    borderColor: tokens.color.slate[500],
                    bgcolor: alpha(tokens.color.slate[700], 0.2),
                  },
                }}
              >
                Download Docs Checklist
              </Button>
            </Box>
          </Stack>

          {/* Quick Metrics Grid */}
          <Grid container spacing={2} sx={{ mt: 2.5, pt: 2, borderTop: `1px solid ${tokens.color.border.subtle}` }}>
            <Grid item xs={6} sm={3}>
              <Typography variant="caption" sx={{ color: tokens.color.slate[400], display: 'block' }}>
                Assistance Scale
              </Typography>
              <Typography variant="subtitle1" sx={{ fontWeight: 800, color: tokens.color.emerald[400], fontSize: '1.05rem' }}>
                {scheme.max_benefit_lakhs
                  ? `Up to ₹${scheme.max_benefit_lakhs >= 100 ? `${(scheme.max_benefit_lakhs / 100).toFixed(1)} Cr` : `${scheme.max_benefit_lakhs} Lakhs`}`
                  : '100% Grant'}
              </Typography>
              <Typography variant="caption" sx={{ color: tokens.color.slate[400], fontSize: '0.72rem' }}>
                {scheme.benefit_percentage ? `${scheme.benefit_percentage}% statutory cover` : 'Government subsidized'}
              </Typography>
            </Grid>

            <Grid item xs={6} sm={3}>
              <Typography variant="caption" sx={{ color: tokens.color.slate[400], display: 'block' }}>
                Application Deadline
              </Typography>
              <Stack direction="row" spacing={0.5} alignItems="center">
                <CalendarTodayOutlinedIcon sx={{ fontSize: 15, color: tokens.color.amber[400] }} />
                <Typography variant="subtitle2" sx={{ fontWeight: 700, color: tokens.color.amber[300], fontSize: '0.9rem' }}>
                  {scheme.deadline || 'March 31, 2027'}
                </Typography>
              </Stack>
              <Typography variant="caption" sx={{ color: tokens.color.slate[400], fontSize: '0.72rem' }}>
                Annual Financial Year window
              </Typography>
            </Grid>

            <Grid item xs={6} sm={3}>
              <Typography variant="caption" sx={{ color: tokens.color.slate[400], display: 'block' }}>
                Target Category
              </Typography>
              <Typography variant="subtitle2" sx={{ fontWeight: 700, color: tokens.color.slate[200], fontSize: '0.9rem' }}>
                {scheme.target_msme_categories && scheme.target_msme_categories.length > 0
                  ? scheme.target_msme_categories.map((c: string) => c.toUpperCase()).join(' / ')
                  : 'Micro, Small & Medium'}
              </Typography>
              <Typography variant="caption" sx={{ color: tokens.color.slate[400], fontSize: '0.72rem' }}>
                Valid MSME Udyam required
              </Typography>
            </Grid>

            <Grid item xs={6} sm={3}>
              <Typography variant="caption" sx={{ color: tokens.color.slate[400], display: 'block' }}>
                Document Readiness
              </Typography>
              <Typography variant="subtitle2" sx={{ fontWeight: 700, color: tokens.color.violet[300], fontSize: '0.9rem' }}>
                {checkedCount} of {requiredDocs.length} Prepared ({progressPercent}%)
              </Typography>
              <LinearProgress
                variant="determinate"
                value={progressPercent}
                sx={{
                  mt: 0.5,
                  height: 6,
                  borderRadius: 3,
                  bgcolor: alpha(tokens.color.slate[700], 0.5),
                  '& .MuiLinearProgress-bar': { bgcolor: tokens.color.violet[500] },
                }}
              />
            </Grid>
          </Grid>
        </CardContent>
      </Card>

      {/* Tabs navigation */}
      <Box sx={{ borderBottom: `1px solid ${tokens.color.border.subtle}`, mb: 3 }}>
        <Tabs
          value={activeTab}
          onChange={(_, val) => setActiveTab(val)}
          textColor="inherit"
          TabIndicatorProps={{ style: { background: tokens.color.violet[400], height: 3 } }}
          sx={{
            '& .MuiTab-root': {
              color: tokens.color.slate[400],
              fontWeight: 600,
              fontSize: '0.85rem',
              textTransform: 'none',
              minHeight: 44,
              '&.Mui-selected': { color: tokens.color.slate[50], fontWeight: 700 },
            },
          }}
        >
          <Tab label={`📋 Required Documents (${requiredDocs.length})`} />
          <Tab label="📖 Objectives & Scope" />
          <Tab label="💰 Scale of Assistance & Slabs" />
          <Tab label="🚀 Application Procedure" />
          <Tab label="⚖️ Statutory Rules & Eligibility" />
        </Tabs>
      </Box>

      {/* TAB 0: MANDATORY REQUIRED DOCUMENTS CHECKLIST */}
      {activeTab === 0 && (
        <Box>
          <Paper
            elevation={0}
            sx={{
              p: 2.5,
              mb: 3,
              borderRadius: '10px',
              bgcolor: tokens.color.surface.card,
              border: `1px solid ${tokens.color.border.subtle}`,
            }}
          >
            <Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" alignItems="center" spacing={2}>
              <Box>
                <Typography variant="subtitle1" sx={{ fontWeight: 700, color: tokens.color.slate[100] }}>
                  Official Document Checklist (From PDF Guidelines)
                </Typography>
                <Typography variant="body2" sx={{ color: tokens.color.slate[400], fontSize: '0.82rem' }}>
                  Check off the documents your enterprise already possesses to verify application readiness.
                </Typography>
              </Box>
              <Button
                size="small"
                variant="outlined"
                onClick={handleExportChecklist}
                startIcon={<FileDownloadOutlinedIcon />}
                sx={{
                  borderColor: tokens.color.border.subtle,
                  color: tokens.color.slate[300],
                  fontSize: '0.78rem',
                  textTransform: 'none',
                }}
              >
                Export Checklist
              </Button>
            </Stack>
          </Paper>

          <Stack spacing={2}>
            {requiredDocs.map((doc: any, index: number) => {
              const isChecked = Boolean(checkedDocs[doc.id])
              return (
                <Card
                  key={doc.id}
                  onClick={() => toggleDoc(doc.id)}
                  sx={{
                    bgcolor: isChecked ? alpha(tokens.color.emerald[500], 0.06) : tokens.color.surface.card,
                    border: `1px solid ${isChecked ? alpha(tokens.color.emerald[500], 0.4) : tokens.color.border.subtle}`,
                    borderRadius: '10px',
                    cursor: 'pointer',
                    transition: 'all 0.15s ease',
                    '&:hover': {
                      borderColor: tokens.color.violet[500],
                      bgcolor: alpha(tokens.color.surface.elevated, 0.7),
                    },
                  }}
                >
                  <CardContent sx={{ p: 2, '&:last-child': { pb: 2 } }}>
                    <Stack direction="row" spacing={2} alignItems="flex-start">
                      <Checkbox
                        checked={isChecked}
                        onChange={() => toggleDoc(doc.id)}
                        sx={{
                          p: 0.5,
                          color: tokens.color.slate[500],
                          '&.Mui-checked': { color: tokens.color.emerald[400] },
                        }}
                      />
                      <Box sx={{ flex: 1 }}>
                        <Stack direction="row" alignItems="center" spacing={1} flexWrap="wrap" sx={{ mb: 0.5 }}>
                          <Typography
                            variant="subtitle2"
                            sx={{
                              fontWeight: 700,
                              color: isChecked ? tokens.color.emerald[300] : tokens.color.slate[100],
                              fontSize: '0.92rem',
                            }}
                          >
                            {index + 1}. {doc.name}
                          </Typography>
                          <Chip
                            label={doc.category}
                            size="small"
                            sx={{
                              bgcolor: alpha(tokens.color.violet[500], 0.12),
                              color: tokens.color.violet[300],
                              fontSize: '0.66rem',
                              height: 20,
                              fontWeight: 600,
                            }}
                          />
                          {doc.mandatory && (
                            <Chip
                              label="MANDATORY"
                              size="small"
                              sx={{
                                bgcolor: alpha(tokens.color.rose[500], 0.12),
                                color: tokens.color.rose[300],
                                fontSize: '0.62rem',
                                height: 18,
                                fontWeight: 700,
                              }}
                            />
                          )}
                        </Stack>
                        <Typography variant="body2" sx={{ color: tokens.color.slate[300], fontSize: '0.82rem', lineHeight: 1.45 }}>
                          {doc.desc}
                        </Typography>
                      </Box>
                    </Stack>
                  </CardContent>
                </Card>
              )
            })}
          </Stack>
        </Box>
      )}

      {/* TAB 1: OBJECTIVES & SCOPE */}
      {activeTab === 1 && (
        <Card sx={{ bgcolor: tokens.color.surface.card, border: `1px solid ${tokens.color.border.subtle}`, borderRadius: '12px', p: 3 }}>
          <Typography variant="h6" sx={{ fontWeight: 800, color: tokens.color.slate[100], mb: 1.5, fontSize: '1.15rem' }}>
            Scheme Background & Objectives
          </Typography>
          <Typography variant="body1" sx={{ color: tokens.color.slate[300], fontSize: '0.9rem', lineHeight: 1.7, mb: 3 }}>
            {scheme.description}
          </Typography>

          {scheme.eligibility_summary && (
            <Box sx={{ p: 2.5, borderRadius: '8px', bgcolor: tokens.color.surface.elevated, border: `1px solid ${tokens.color.border.subtle}` }}>
              <Typography variant="subtitle2" sx={{ fontWeight: 700, color: tokens.color.violet[300], mb: 1 }}>
                Eligibility Summary (Statutory Source):
              </Typography>
              <Typography variant="body2" sx={{ color: tokens.color.slate[300], fontSize: '0.85rem', lineHeight: 1.6 }}>
                {scheme.eligibility_summary}
              </Typography>
            </Box>
          )}

          {scheme.target_sectors && scheme.target_sectors.length > 0 && (
            <Box sx={{ mt: 3 }}>
              <Typography variant="caption" sx={{ color: tokens.color.slate[400], fontWeight: 700, display: 'block', mb: 1 }}>
                COVERED SECTORS & ACTIVITIES:
              </Typography>
              <Stack direction="row" spacing={1} flexWrap="wrap" gap={1}>
                {scheme.target_sectors.map((sec: string) => (
                  <Chip
                    key={sec}
                    label={sec.toUpperCase()}
                    size="small"
                    sx={{
                      bgcolor: alpha(tokens.color.slate[700], 0.5),
                      color: tokens.color.slate[300],
                      fontSize: '0.72rem',
                    }}
                  />
                ))}
              </Stack>
            </Box>
          )}
        </Card>
      )}

      {/* TAB 2: SCALE OF ASSISTANCE & SLABS */}
      {activeTab === 2 && (
        <Card sx={{ bgcolor: tokens.color.surface.card, border: `1px solid ${tokens.color.border.subtle}`, borderRadius: '12px', p: 3 }}>
          <Typography variant="h6" sx={{ fontWeight: 800, color: tokens.color.slate[100], mb: 2, fontSize: '1.15rem' }}>
            Scale of Financial Assistance & Slabs
          </Typography>
          <Typography variant="body1" sx={{ color: tokens.color.slate[300], fontSize: '0.9rem', lineHeight: 1.6, mb: 3 }}>
            {scheme.benefit_description}
          </Typography>

          {scheme.benefits && scheme.benefits.length > 0 && (
            <Grid container spacing={2}>
              {scheme.benefits.map((b: any, i: number) => (
                <Grid item xs={12} md={6} key={i}>
                  <Card sx={{ bgcolor: tokens.color.surface.elevated, border: `1px solid ${tokens.color.border.subtle}`, p: 2.5, borderRadius: '10px' }}>
                    <Typography variant="subtitle2" sx={{ fontWeight: 700, color: tokens.color.emerald[300], mb: 0.5 }}>
                      {b.benefit_name}
                    </Typography>
                    <Typography variant="h6" sx={{ fontWeight: 800, color: tokens.color.slate[50], fontSize: '1.1rem', mb: 1 }}>
                      {b.amount_or_percentage}
                    </Typography>
                    {b.conditions && (
                      <Typography variant="caption" sx={{ color: tokens.color.slate[400], display: 'block', mb: 1 }}>
                        Condition: {b.conditions}
                      </Typography>
                    )}
                    {b.source_clause && (
                      <Typography variant="caption" sx={{ color: tokens.color.violet[300], display: 'block', fontSize: '0.72rem' }}>
                        Clause: {b.source_clause}
                      </Typography>
                    )}
                  </Card>
                </Grid>
              ))}
            </Grid>
          )}
        </Card>
      )}

      {/* TAB 3: STEP-BY-STEP APPLICATION PROCEDURE */}
      {activeTab === 3 && (
        <Card sx={{ bgcolor: tokens.color.surface.card, border: `1px solid ${tokens.color.border.subtle}`, borderRadius: '12px', p: 3 }}>
          <Typography variant="h6" sx={{ fontWeight: 800, color: tokens.color.slate[100], mb: 1, fontSize: '1.15rem' }}>
            Step-by-Step Application Procedure
          </Typography>
          <Typography variant="body2" sx={{ color: tokens.color.slate[400], mb: 3 }}>
            Follow the sequential statutory process as specified in the official ministry guidelines.
          </Typography>

          <Stack spacing={2}>
            {(scheme.application_steps || [
              'Verify MSME Udyam Registration & IEC Status.',
              'Compile all statutory CA certificates & required documents from the checklist.',
              'Submit online declaration or application on the designated government portal.',
              'Coordinate with Member Lending Institution / District Industries Centre for appraisal.',
              'Receive sanction, unique identification number (UIN/CGPAN), and grant disbursement.',
            ]).map((step: string, index: number) => (
              <Box
                key={index}
                sx={{
                  display: 'flex',
                  alignItems: 'flex-start',
                  gap: 2,
                  p: 2,
                  borderRadius: '10px',
                  bgcolor: tokens.color.surface.elevated,
                  border: `1px solid ${tokens.color.border.subtle}`,
                }}
              >
                <Box
                  sx={{
                    width: 32,
                    height: 32,
                    borderRadius: '50%',
                    bgcolor: tokens.color.violet[500],
                    color: '#FFFFFF',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    fontWeight: 800,
                    fontSize: '0.85rem',
                    flexShrink: 0,
                  }}
                >
                  {index + 1}
                </Box>
                <Typography variant="body2" sx={{ color: tokens.color.slate[200], fontSize: '0.88rem', lineHeight: 1.5, pt: 0.5 }}>
                  {step}
                </Typography>
              </Box>
            ))}
          </Stack>
        </Card>
      )}

      {/* TAB 4: STATUTORY RULES & ELIGIBILITY */}
      {activeTab === 4 && (
        <Card sx={{ bgcolor: tokens.color.surface.card, border: `1px solid ${tokens.color.border.subtle}`, borderRadius: '12px', p: 3 }}>
          <Typography variant="h6" sx={{ fontWeight: 800, color: tokens.color.slate[100], mb: 2, fontSize: '1.15rem' }}>
            Statutory Eligibility Rules & Evidence
          </Typography>
          {scheme.rules && scheme.rules.length > 0 ? (
            <Stack spacing={2}>
              {scheme.rules.map((rule: any, i: number) => (
                <Box
                  key={i}
                  sx={{
                    p: 2,
                    borderRadius: '8px',
                    bgcolor: tokens.color.surface.elevated,
                    border: `1px solid ${tokens.color.border.subtle}`,
                  }}
                >
                  <Stack direction="row" justifyContent="space-between" alignItems="center" sx={{ mb: 0.75 }}>
                    <Typography variant="subtitle2" sx={{ fontWeight: 700, color: tokens.color.slate[200] }}>
                      {rule.display_label || rule.rule_name}
                    </Typography>
                    <Chip
                      label={rule.importance.toUpperCase()}
                      size="small"
                      sx={{
                        bgcolor: alpha(tokens.color.violet[500], 0.15),
                        color: tokens.color.violet[300],
                        fontSize: '0.64rem',
                        height: 20,
                        fontWeight: 700,
                      }}
                    />
                  </Stack>
                  <Typography variant="caption" sx={{ color: tokens.color.slate[400], display: 'block', mb: 0.5 }}>
                    Clause: {rule.source_clause}
                  </Typography>
                  {rule.source_document && (
                    <Typography variant="caption" sx={{ color: tokens.color.slate[500], display: 'block', fontSize: '0.7rem' }}>
                      Citation: {rule.source_document}
                    </Typography>
                  )}
                </Box>
              ))}
            </Stack>
          ) : (
            <Typography variant="body2" sx={{ color: tokens.color.slate[400] }}>
              General MSME eligibility rules apply in accordance with Ministry of MSME guidelines.
            </Typography>
          )}
        </Card>
      )}
    </Box>
  )
}

export default SchemeDetailPage
