import React, { useState } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import {
  Box,
  Typography,
  Button,
  Stack,
  Card,
  CardContent,
  Chip,
  Grid,
  Divider,
  Paper,
  Checkbox,
  LinearProgress,
  CircularProgress,
} from '@mui/material'
import ArrowBackIcon from '@mui/icons-material/ArrowBack'
import CalendarTodayOutlinedIcon from '@mui/icons-material/CalendarTodayOutlined'
import VerifiedUserIcon from '@mui/icons-material/VerifiedUser'
import OpenInNewIcon from '@mui/icons-material/OpenInNew'
import StarIcon from '@mui/icons-material/Star'
import CheckCircleOutlineIcon from '@mui/icons-material/CheckCircleOutline'
import CancelOutlinedIcon from '@mui/icons-material/CancelOutlined'
import AssignmentTurnedInIcon from '@mui/icons-material/AssignmentTurnedIn'
import FileDownloadOutlinedIcon from '@mui/icons-material/FileDownloadOutlined'
import InfoOutlinedIcon from '@mui/icons-material/InfoOutlined'
import PaymentsOutlinedIcon from '@mui/icons-material/PaymentsOutlined'
import FactCheckOutlinedIcon from '@mui/icons-material/FactCheckOutlined'
import DomainOutlinedIcon from '@mui/icons-material/DomainOutlined'
import GavelOutlinedIcon from '@mui/icons-material/GavelOutlined'
import AutoAwesomeIcon from '@mui/icons-material/AutoAwesome'
import { tokens } from '../theme/tokens'
import { useScheme } from '../api/hooks'
import { toast } from 'sonner'
import { useLanguage } from '../i18n'

export const SchemeDetailPage: React.FC = () => {
  const { id } = useParams<{ id: string }>()
  const navigate = useNavigate()
  const { lang, t } = useLanguage()
  const { data: scheme, isLoading, error } = useScheme(id)
  
  const [activeSection, setActiveSection] = useState<string>('all')
  const [checkedDocs, setCheckedDocs] = useState<Record<string, boolean>>({})

  const toggleDoc = (docId: string) => {
    setCheckedDocs((prev) => ({
      ...prev,
      [docId]: !prev[docId],
    }))
  }

  const handleExportChecklist = () => {
    if (!scheme) return
    const docs = scheme.required_documents || []
    const checklistText =
      `UDYAMNITI - STATUTORY SCHEME DOCUMENT CHECKLIST\n` +
      `Scheme: ${scheme.name} (${scheme.scheme_code})\n` +
      `Issuing Authority: ${scheme.ministry || 'Ministry of MSME'}\n` +
      `Nodal Implementing Agency: ${scheme.implementing_agency || 'District Industries Centre (DIC)'}\n` +
      `Official Reference: ${scheme.gazette_notification || 'Official Gazette'}\n` +
      `Application Deadline: ${scheme.deadline || 'March 31, 2027'}\n` +
      `Official Portal: ${scheme.official_portal_url || 'https://msme.gov.in'}\n` +
      `------------------------------------------------------------------\n\n` +
      `MANDATORY STATUTORY DOCUMENTS REQUIRED:\n` +
      docs
        .map(
          (d: any, idx: number) =>
            `[${checkedDocs[d.id] ? 'X' : ' '}] ${idx + 1}. ${d.name}\n    Category: ${d.category} | Mandatory: ${
              d.mandatory ? 'YES' : 'Optional'
            }\n    Verification Notes: ${d.desc}`
        )
        .join('\n\n') +
      `\n\n------------------------------------------------------------------\n` +
      `Generated by UdyamNiti Platform on ${new Date().toLocaleDateString()}`

    const blob = new Blob([checklistText], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `${scheme.scheme_code}_document_checklist.txt`
    link.click()
    URL.revokeObjectURL(url)
    toast.success('Document checklist downloaded successfully!')
  }

  const scrollToAnchor = (sectionId: string) => {
    setActiveSection(sectionId)
    const el = document.getElementById(sectionId)
    if (el) {
      el.scrollIntoView({ behavior: 'smooth', block: 'start' })
    }
  }

  if (isLoading) {
    return (
      <Box sx={{ display: 'flex', flexDirection: 'column', justifyContent: 'center', alignItems: 'center', minHeight: '60vh', gap: 2 }}>
        <CircularProgress size={42} sx={{ color: '#0F2E59' }} />
        <Typography variant="body2" sx={{ color: '#64748B' }}>
          Loading official scheme gazette intelligence...
        </Typography>
      </Box>
    )
  }

  if (error || !scheme) {
    return (
      <Box sx={{ maxWidth: 800, mx: 'auto', px: 3, py: 8, textAlign: 'center' }}>
        <Typography variant="h5" sx={{ color: '#0F2E59', fontWeight: 800, mb: 1 }}>
          Scheme details could not be retrieved.
        </Typography>
        <Typography variant="body2" sx={{ color: '#64748B', mb: 3 }}>
          The requested scheme code or identifier was not found in the active database.
        </Typography>
        <Button
          variant="contained"
          startIcon={<ArrowBackIcon />}
          onClick={() => navigate('/dashboard')}
          sx={{ bgcolor: '#0F2E59', textTransform: 'none', fontWeight: 700 }}
        >
          Return to Schemes Dashboard
        </Button>
      </Box>
    )
  }

  const requiredDocs = scheme.required_documents || []
  const checkedCount = requiredDocs.filter((d: any) => checkedDocs[d.id]).length
  const progressPercent = requiredDocs.length > 0 ? Math.round((checkedCount / requiredDocs.length) * 100) : 0

  const navItems = [
    { id: 'all', label: t('allDetails'), icon: <AutoAwesomeIcon sx={{ fontSize: 16 }} /> },
    { id: 'overview', label: t('schemeOverview'), icon: <InfoOutlinedIcon sx={{ fontSize: 16 }} /> },
    { id: 'eligibility', label: t('whoIsEligible'), icon: <FactCheckOutlinedIcon sx={{ fontSize: 16 }} /> },
    { id: 'benefits', label: t('benefitsFinancialAssistance'), icon: <PaymentsOutlinedIcon sx={{ fontSize: 16 }} /> },
    { id: 'documents', label: `${t('requiredDocuments')} (${requiredDocs.length})`, icon: <AssignmentTurnedInIcon sx={{ fontSize: 16 }} /> },
    { id: 'procedure', label: t('applicationProcedure'), icon: <DomainOutlinedIcon sx={{ fontSize: 16 }} /> },
    { id: 'gazette', label: t('officialGazette'), icon: <GavelOutlinedIcon sx={{ fontSize: 16 }} /> },
  ]

  return (
    <Box sx={{ maxWidth: 1240, mx: 'auto', px: { xs: 2, sm: 3, md: 4 }, py: 3.5, bgcolor: '#F8FAFC', color: '#0F172A' }}>
      {/* ─── TOP BREADCRUMB & BACK BUTTON ─── */}
      <Stack direction="row" alignItems="center" spacing={1.5} sx={{ mb: 2.5 }}>
        <Button
          size="small"
          startIcon={<ArrowBackIcon />}
          onClick={() => navigate('/dashboard')}
          sx={{
            color: '#0F2E59',
            textTransform: 'none',
            fontSize: '0.86rem',
            fontWeight: 700,
            bgcolor: '#FFFFFF',
            border: '1px solid #CBD5E1',
            borderRadius: '6px',
            px: 1.5,
            py: 0.4,
            '&:hover': { bgcolor: '#F1F5F9' },
          }}
        >
          {t('backToSchemes')}
        </Button>
        <Typography variant="caption" sx={{ color: '#94A3B8' }}>
          /
        </Typography>
        <Chip
          label={scheme.level === 'state_gujarat' ? 'Gujarat State Government' : 'Central Government'}
          size="small"
          sx={{
            height: 24,
            fontSize: '0.72rem',
            bgcolor: scheme.level === 'state_gujarat' ? '#ECFDF5' : '#EFF6FF',
            color: scheme.level === 'state_gujarat' ? '#065F46' : '#1E40AF',
            border: `1px solid ${scheme.level === 'state_gujarat' ? '#A7F3D0' : '#BFDBFE'}`,
            fontWeight: 700,
          }}
        />
        <Typography variant="body2" sx={{ color: '#475569', fontWeight: 600 }} noWrap>
          {scheme.short_name || scheme.scheme_code}
        </Typography>
      </Stack>

      {/* ─── HERO CARD: OFFICIAL SCHEME IDENTITY ─── */}
      <Card
        sx={{
          mb: 3.5,
          borderRadius: '16px',
          bgcolor: '#FFFFFF',
          border: '1px solid #CBD5E1',
          boxShadow: '0 4px 20px rgba(15, 23, 42, 0.06)',
          overflow: 'hidden',
          position: 'relative',
        }}
      >
        {/* Top Accent Strip */}
        <Box
          sx={{
            position: 'absolute',
            top: 0,
            left: 0,
            right: 0,
            height: 5,
            background: 'linear-gradient(90deg, #FF9933 0%, #0F2E59 50%, #138808 100%)',
          }}
        />
        <CardContent sx={{ p: { xs: 2.5, sm: 4 }, pt: { xs: 3.5, sm: 4.5 } }}>
          <Stack direction={{ xs: 'column', md: 'row' }} justifyContent="space-between" spacing={3}>
            <Box sx={{ flex: 1 }}>
              {/* Badges Stack */}
              <Stack direction="row" spacing={1} alignItems="center" flexWrap="wrap" sx={{ mb: 2, gap: 0.8 }}>
                {scheme.is_best_deal && (
                  <Chip
                    icon={<StarIcon sx={{ fontSize: '13px !important', color: '#92400E !important' }} />}
                    label="TOP RECOMMENDED SCHEME"
                    size="small"
                    sx={{
                      bgcolor: '#FEF3C7',
                      color: '#92400E',
                      border: '1px solid #FDE68A',
                      fontWeight: 800,
                      fontSize: '0.72rem',
                      height: 24,
                    }}
                  />
                )}
                <Chip
                  label={scheme.scheme_code}
                  size="small"
                  sx={{
                    bgcolor: '#F1F5F9',
                    color: '#0F2E59',
                    border: '1px solid #CBD5E1',
                    fontSize: '0.75rem',
                    height: 24,
                    fontWeight: 800,
                    fontFamily: tokens.font.mono,
                  }}
                />
                <Chip
                  label={scheme.level === 'state_gujarat' ? 'Gujarat State Government' : 'Central Government'}
                  size="small"
                  sx={{
                    bgcolor: scheme.level === 'state_gujarat' ? '#ECFDF5' : '#EFF6FF',
                    color: scheme.level === 'state_gujarat' ? '#065F46' : '#1E40AF',
                    border: `1px solid ${scheme.level === 'state_gujarat' ? '#A7F3D0' : '#BFDBFE'}`,
                    fontSize: '0.75rem',
                    height: 24,
                    fontWeight: 700,
                  }}
                />
                <Chip
                  icon={<VerifiedUserIcon sx={{ fontSize: '13px !important', color: '#065F46 !important' }} />}
                  label="Official Gazette Verified"
                  size="small"
                  sx={{
                    bgcolor: '#ECFDF5',
                    color: '#065F46',
                    border: '1px solid #A7F3D0',
                    fontSize: '0.75rem',
                    height: 24,
                    fontWeight: 700,
                  }}
                />
              </Stack>

              {/* Scheme Main Title (Crisp High-Contrast Dark Navy) */}
              <Typography
                variant="h4"
                component="h1"
                sx={{
                  fontWeight: 800,
                  color: '#0F2E59',
                  fontSize: { xs: '1.4rem', sm: '1.75rem', md: '2.1rem' },
                  lineHeight: 1.25,
                  mb: 2,
                }}
              >
                {scheme.name}
              </Typography>

              {/* Ministry & Nodal Agency Details */}
              <Typography variant="body1" sx={{ color: '#1E293B', fontSize: '0.96rem', mb: 1, lineHeight: 1.5 }}>
                <strong style={{ color: '#0F2E59' }}>Ministry / Issuing Department:</strong> {scheme.ministry}
              </Typography>
              {scheme.implementing_agency && (
                <Typography variant="body2" sx={{ color: '#334155', fontSize: '0.9rem', mb: 1 }}>
                  <strong style={{ color: '#0F2E59' }}>Nodal Implementing Agency:</strong> {scheme.implementing_agency}
                </Typography>
              )}
              {scheme.gazette_notification && (
                <Box sx={{ mt: 1.5, p: 1.5, bgcolor: '#F8FAFC', border: '1px solid #E2E8F0', borderRadius: '8px' }}>
                  <Typography variant="caption" sx={{ color: '#1E40AF', display: 'block', fontSize: '0.84rem', fontWeight: 600 }}>
                    <strong>Official Reference Citation:</strong> {scheme.gazette_notification}
                  </Typography>
                </Box>
              )}
            </Box>

            {/* Quick Actions Card on Right (Clean Light Box) */}
            <Box
              sx={{
                display: 'flex',
                flexDirection: 'column',
                gap: 1.5,
                minWidth: { md: 270 },
                p: { xs: 2, sm: 2.5 },
                bgcolor: '#F8FAFC',
                border: '1px solid #CBD5E1',
                borderRadius: '12px',
                height: 'fit-content',
                boxShadow: '0 2px 8px rgba(15, 23, 42, 0.04)',
              }}
            >
              <Typography variant="caption" sx={{ color: '#0F2E59', fontWeight: 800, letterSpacing: '0.04em', textTransform: 'uppercase' }}>
                DIRECT ACTIONS
              </Typography>

              {scheme.official_portal_url && (
                <Button
                  variant="contained"
                  component="a"
                  href={scheme.official_portal_url}
                  target="_blank"
                  rel="noreferrer"
                  endIcon={<OpenInNewIcon sx={{ fontSize: 16 }} />}
                  sx={{
                    bgcolor: '#0F2E59',
                    color: '#FFFFFF',
                    fontWeight: 700,
                    fontSize: '0.88rem',
                    py: 1.1,
                    borderRadius: '8px',
                    textTransform: 'none',
                    boxShadow: '0 3px 10px rgba(15, 46, 89, 0.25)',
                    '&:hover': { bgcolor: '#0A1E3A' },
                  }}
                >
                  Apply on Official Portal
                </Button>
              )}

              <Button
                variant="outlined"
                startIcon={<FileDownloadOutlinedIcon />}
                onClick={handleExportChecklist}
                sx={{
                  borderColor: '#0F2E59',
                  color: '#0F2E59',
                  fontWeight: 700,
                  fontSize: '0.84rem',
                  py: 1,
                  borderRadius: '8px',
                  textTransform: 'none',
                  bgcolor: '#FFFFFF',
                  '&:hover': {
                    borderColor: '#0A1E3A',
                    bgcolor: '#F1F5F9',
                  },
                }}
              >
                {t('downloadChecklist')}
              </Button>
            </Box>
          </Stack>

          <Divider sx={{ my: 3, borderColor: '#E2E8F0' }} />

          {/* ─── 4 EXECUTIVE KPI HIGHLIGHT CARDS (VIBRANT LIGHT CONTRAST) ─── */}
          <Grid container spacing={2}>
            {/* Card 1: Benefits */}
            <Grid item xs={12} sm={6} md={3}>
              <Paper
                elevation={0}
                sx={{
                  p: 2.2,
                  bgcolor: '#ECFDF5',
                  border: '1px solid #A7F3D0',
                  borderRadius: '10px',
                  height: '100%',
                }}
              >
                <Stack direction="row" alignItems="center" spacing={1} sx={{ mb: 0.5 }}>
                  <PaymentsOutlinedIcon sx={{ color: '#059669', fontSize: 18 }} />
                  <Typography variant="caption" sx={{ color: '#047857', fontWeight: 800, textTransform: 'uppercase' }}>
                    1. Financial Benefit
                  </Typography>
                </Stack>
                <Typography variant="h6" sx={{ fontWeight: 800, color: '#065F46', fontSize: '1.3rem', mb: 0.5 }}>
                  {scheme.max_benefit_lakhs
                    ? `Up to ₹${scheme.max_benefit_lakhs >= 100 ? `${(scheme.max_benefit_lakhs / 100).toFixed(1)} Cr` : `${scheme.max_benefit_lakhs} Lakhs`}`
                    : '100% Grant'}
                </Typography>
                <Typography variant="caption" sx={{ color: '#047857', display: 'block', fontSize: '0.82rem', fontWeight: 600 }}>
                  {scheme.benefit_percentage ? `${scheme.benefit_percentage}% Statutory Assistance` : 'Direct DBT Subsidized'}
                </Typography>
              </Paper>
            </Grid>

            {/* Card 2: Who is Eligible */}
            <Grid item xs={12} sm={6} md={3}>
              <Paper
                elevation={0}
                sx={{
                  p: 2.2,
                  bgcolor: '#EFF6FF',
                  border: '1px solid #BFDBFE',
                  borderRadius: '10px',
                  height: '100%',
                }}
              >
                <Stack direction="row" alignItems="center" spacing={1} sx={{ mb: 0.5 }}>
                  <FactCheckOutlinedIcon sx={{ color: '#1D4ED8', fontSize: 18 }} />
                  <Typography variant="caption" sx={{ color: '#1E40AF', fontWeight: 800, textTransform: 'uppercase' }}>
                    2. Who is Eligible
                  </Typography>
                </Stack>
                <Typography variant="h6" sx={{ fontWeight: 800, color: '#0F2E59', fontSize: '1.1rem', mb: 0.5 }}>
                  {scheme.target_msme_categories && scheme.target_msme_categories.length > 0
                    ? scheme.target_msme_categories.map((c: string) => c.toUpperCase()).join(' / ')
                    : 'MICRO / SMALL / MEDIUM'}
                </Typography>
                <Typography variant="caption" sx={{ color: '#1E3A8A', display: 'block', fontSize: '0.82rem', fontWeight: 600 }}>
                  Active MSME Udyam Registration
                </Typography>
              </Paper>
            </Grid>

            {/* Card 3: Deadline */}
            <Grid item xs={12} sm={6} md={3}>
              <Paper
                elevation={0}
                sx={{
                  p: 2.2,
                  bgcolor: '#FFFBEB',
                  border: '1px solid #FDE68A',
                  borderRadius: '10px',
                  height: '100%',
                }}
              >
                <Stack direction="row" alignItems="center" spacing={1} sx={{ mb: 0.5 }}>
                  <CalendarTodayOutlinedIcon sx={{ color: '#D97706', fontSize: 18 }} />
                  <Typography variant="caption" sx={{ color: '#92400E', fontWeight: 800, textTransform: 'uppercase' }}>
                    3. Application Window
                  </Typography>
                </Stack>
                <Typography variant="h6" sx={{ fontWeight: 800, color: '#78350F', fontSize: '1.05rem', mb: 0.5 }}>
                  {scheme.deadline || 'Valid till March 2027'}
                </Typography>
                <Typography variant="caption" sx={{ color: '#92400E', display: 'block', fontSize: '0.82rem', fontWeight: 600 }}>
                  Annual Financial Year Window
                </Typography>
              </Paper>
            </Grid>

            {/* Card 4: Documents Readiness */}
            <Grid item xs={12} sm={6} md={3}>
              <Paper
                elevation={0}
                sx={{
                  p: 2.2,
                  bgcolor: '#EEF2FF',
                  border: '1px solid #C7D2FE',
                  borderRadius: '10px',
                  height: '100%',
                }}
              >
                <Stack direction="row" alignItems="center" spacing={1} sx={{ mb: 0.5 }}>
                  <AssignmentTurnedInIcon sx={{ color: '#4338CA', fontSize: 18 }} />
                  <Typography variant="caption" sx={{ color: '#3730A3', fontWeight: 800, textTransform: 'uppercase' }}>
                    4. Statutory Documents
                  </Typography>
                </Stack>
                <Typography variant="h6" sx={{ fontWeight: 800, color: '#312E81', fontSize: '1.15rem', mb: 0.5 }}>
                  {checkedCount} / {requiredDocs.length} Prepared ({progressPercent}%)
                </Typography>
                <LinearProgress
                  variant="determinate"
                  value={progressPercent}
                  sx={{
                    height: 6,
                    borderRadius: 3,
                    bgcolor: '#E0E7FF',
                    '& .MuiLinearProgress-bar': { bgcolor: '#4338CA' },
                  }}
                />
              </Paper>
            </Grid>
          </Grid>
        </CardContent>
      </Card>

      {/* ─── STICKY SECTION QUICK JUMP BAR (CLEAN WHITE) ─── */}
      <Box
        sx={{
          position: 'sticky',
          top: 64,
          zIndex: 10,
          bgcolor: '#FFFFFF',
          border: '1px solid #CBD5E1',
          borderRadius: '12px',
          p: 0.8,
          mb: 4,
          display: 'flex',
          gap: 0.8,
          overflowX: 'auto',
          boxShadow: '0 4px 14px rgba(15, 23, 42, 0.06)',
        }}
      >
        {navItems.map((item) => (
          <Button
            key={item.id}
            size="small"
            onClick={() => scrollToAnchor(item.id)}
            startIcon={item.icon}
            sx={{
              px: 2,
              py: 0.8,
              borderRadius: '8px',
              textTransform: 'none',
              fontWeight: activeSection === item.id ? 800 : 600,
              fontSize: '0.84rem',
              whiteSpace: 'nowrap',
              color: activeSection === item.id ? '#FFFFFF' : '#1E293B',
              bgcolor: activeSection === item.id ? '#0F2E59' : 'transparent',
              '&:hover': {
                color: activeSection === item.id ? '#FFFFFF' : '#0F2E59',
                bgcolor: activeSection === item.id ? '#0A1E3A' : '#F1F5F9',
              },
            }}
          >
            {item.label}
          </Button>
        ))}
      </Box>

      {/* ─── SECTION 1: WHAT IS THIS SCHEME ABOUT? ─── */}
      <Box id="overview" sx={{ mb: 4, scrollMarginTop: 130 }}>
        <Card sx={{ bgcolor: '#FFFFFF', border: '1px solid #CBD5E1', borderRadius: '14px', p: 3.5, boxShadow: '0 2px 8px rgba(15, 23, 42, 0.04)' }}>
          <Stack direction="row" alignItems="center" spacing={1.5} sx={{ mb: 2 }}>
            <Box
              sx={{
                width: 36,
                height: 36,
                borderRadius: '8px',
                bgcolor: '#EFF6FF',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
              }}
            >
              <InfoOutlinedIcon sx={{ color: '#1E40AF', fontSize: 22 }} />
            </Box>
            <Typography variant="h5" sx={{ fontWeight: 800, color: '#0F2E59', fontSize: '1.3rem' }}>
              1. What is this Scheme About? (Background & Objectives)
            </Typography>
          </Stack>

          <Typography variant="body1" sx={{ color: '#1E293B', fontSize: '0.98rem', lineHeight: 1.75, mb: 3 }}>
            {scheme.description}
          </Typography>

          {/* Covered Sectors */}
          {scheme.target_sectors && scheme.target_sectors.length > 0 && (
            <Box sx={{ mt: 2, p: 2.2, bgcolor: '#F8FAFC', borderRadius: '10px', border: '1px solid #E2E8F0' }}>
              <Typography variant="caption" sx={{ color: '#0F2E59', fontWeight: 800, display: 'block', mb: 1.2, letterSpacing: '0.04em' }}>
                ELIGIBLE SECTORS & INDUSTRIAL ACTIVITIES:
              </Typography>
              <Stack direction="row" spacing={1} flexWrap="wrap" gap={1}>
                {scheme.target_sectors.map((sec: string) => (
                  <Chip
                    key={sec}
                    label={sec.toUpperCase()}
                    size="small"
                    sx={{
                      bgcolor: '#EFF6FF',
                      color: '#1E40AF',
                      border: '1px solid #BFDBFE',
                      fontSize: '0.78rem',
                      fontWeight: 700,
                    }}
                  />
                ))}
              </Stack>
            </Box>
          )}
        </Card>
      </Box>

      {/* ─── SECTION 2: WHO IS ELIGIBLE? ─── */}
      <Box id="eligibility" sx={{ mb: 4, scrollMarginTop: 130 }}>
        <Card sx={{ bgcolor: '#FFFFFF', border: '1px solid #CBD5E1', borderRadius: '14px', p: 3.5, boxShadow: '0 2px 8px rgba(15, 23, 42, 0.04)' }}>
          <Stack direction="row" alignItems="center" spacing={1.5} sx={{ mb: 2 }}>
            <Box
              sx={{
                width: 36,
                height: 36,
                borderRadius: '8px',
                bgcolor: '#EFF6FF',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
              }}
            >
              <FactCheckOutlinedIcon sx={{ color: '#1D4ED8', fontSize: 22 }} />
            </Box>
            <Typography variant="h5" sx={{ fontWeight: 800, color: '#0F2E59', fontSize: '1.3rem' }}>
              2. Who is Eligible? (Eligibility Criteria & Rules)
            </Typography>
          </Stack>

          {/* Statutory Summary */}
          {scheme.eligibility_summary && (
            <Box
              sx={{
                p: 2.5,
                borderRadius: '10px',
                bgcolor: '#F0F9FF',
                border: '1px solid #BAE6FD',
                mb: 3,
              }}
            >
              <Typography variant="subtitle2" sx={{ fontWeight: 800, color: '#0369A1', mb: 1 }}>
                Official Gazette Eligibility Summary:
              </Typography>
              <Typography variant="body2" sx={{ color: '#0F172A', fontSize: '0.94rem', lineHeight: 1.7, whiteSpace: 'pre-line' }}>
                {scheme.eligibility_summary}
              </Typography>
            </Box>
          )}

          {/* Detailed Invariant Rules */}
          <Typography variant="subtitle1" sx={{ fontWeight: 800, color: '#0F2E59', mb: 1.5 }}>
            Statutory Rule Invariants Checked by System:
          </Typography>

          <Grid container spacing={2}>
            {(scheme.rules || []).map((rule: any, i: number) => (
              <Grid item xs={12} md={6} key={i}>
                <Paper
                  elevation={0}
                  sx={{
                    p: 2.2,
                    bgcolor: '#F8FAFC',
                    border: '1px solid #E2E8F0',
                    borderRadius: '10px',
                    height: '100%',
                  }}
                >
                  <Stack direction="row" justifyContent="space-between" alignItems="center" sx={{ mb: 0.75 }}>
                    <Stack direction="row" alignItems="center" spacing={1}>
                      <CheckCircleOutlineIcon sx={{ color: '#059669', fontSize: 18 }} />
                      <Typography variant="subtitle2" sx={{ fontWeight: 800, color: '#0F2E59', fontSize: '0.92rem' }}>
                        {rule.display_label || rule.rule_name}
                      </Typography>
                    </Stack>
                    <Chip
                      label={(rule.importance || 'MANDATORY').toUpperCase()}
                      size="small"
                      sx={{
                        bgcolor: rule.importance === 'mandatory' ? '#FEF2F2' : '#EFF6FF',
                        color: rule.importance === 'mandatory' ? '#991B1B' : '#1E40AF',
                        border: `1px solid ${rule.importance === 'mandatory' ? '#FECACA' : '#BFDBFE'}`,
                        fontSize: '0.68rem',
                        fontWeight: 800,
                        height: 20,
                      }}
                    />
                  </Stack>
                  <Typography variant="caption" sx={{ color: '#475569', display: 'block', fontSize: '0.82rem' }}>
                    {rule.source_clause || 'Statutory condition verified from government gazette.'}
                  </Typography>
                </Paper>
              </Grid>
            ))}
          </Grid>

          {/* Ineligibility Warning Box */}
          <Box
            sx={{
              mt: 3,
              p: 2.2,
              borderRadius: '10px',
              bgcolor: '#FEF2F2',
              border: '1px solid #FECACA',
              display: 'flex',
              gap: 1.5,
              alignItems: 'flex-start',
            }}
          >
            <CancelOutlinedIcon sx={{ color: '#DC2626', fontSize: 22, mt: 0.2 }} />
            <Box>
              <Typography variant="subtitle2" sx={{ color: '#991B1B', fontWeight: 800, fontSize: '0.92rem' }}>
                Who is Ineligible / Excluded:
              </Typography>
              <Typography variant="body2" sx={{ color: '#7F1D1D', fontSize: '0.86rem', lineHeight: 1.6 }}>
                Enterprises classified as Non-Performing Assets (NPA), willful bank defaulters, units that have already availed overlapping capital subsidies for the exact same machinery under duplicate billing, or non-MSME large enterprises.
              </Typography>
            </Box>
          </Box>
        </Card>
      </Box>

      {/* ─── SECTION 3: WHICH BENEFITS DOES THIS SCHEME GIVE? ─── */}
      <Box id="benefits" sx={{ mb: 4, scrollMarginTop: 130 }}>
        <Card sx={{ bgcolor: '#FFFFFF', border: '1px solid #CBD5E1', borderRadius: '14px', p: 3.5, boxShadow: '0 2px 8px rgba(15, 23, 42, 0.04)' }}>
          <Stack direction="row" alignItems="center" spacing={1.5} sx={{ mb: 2 }}>
            <Box
              sx={{
                width: 36,
                height: 36,
                borderRadius: '8px',
                bgcolor: '#ECFDF5',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
              }}
            >
              <PaymentsOutlinedIcon sx={{ color: '#059669', fontSize: 22 }} />
            </Box>
            <Typography variant="h5" sx={{ fontWeight: 800, color: '#0F2E59', fontSize: '1.3rem' }}>
              3. Which Benefits Does This Scheme Give? (Scale of Financial Assistance & Slabs)
            </Typography>
          </Stack>

          <Typography variant="body1" sx={{ color: '#1E293B', fontSize: '0.96rem', lineHeight: 1.7, mb: 3 }}>
            {scheme.benefit_description}
          </Typography>

          {/* Slabs Grid */}
          <Grid container spacing={2}>
            {(scheme.benefits || [
              {
                benefit_name: 'Primary Financial Assistance Slab',
                amount_or_percentage: scheme.max_benefit_lakhs ? `Up to ₹${scheme.max_benefit_lakhs} Lakhs` : '100% Grant',
                conditions: 'Applicable for eligible MSME units compliant with gazette criteria.',
                source_clause: scheme.gazette_notification || 'Official Scheme Guideline Section 3',
              },
            ]).map((b: any, i: number) => (
              <Grid item xs={12} md={6} key={i}>
                <Paper
                  elevation={0}
                  sx={{
                    p: 2.5,
                    bgcolor: '#F8FAFC',
                    border: '1px solid #A7F3D0',
                    borderRadius: '12px',
                    height: '100%',
                  }}
                >
                  <Typography variant="caption" sx={{ color: '#047857', fontWeight: 800, textTransform: 'uppercase', display: 'block', mb: 0.5 }}>
                    BENEFIT HEAD {i + 1}
                  </Typography>
                  <Typography variant="h6" sx={{ fontWeight: 800, color: '#0F2E59', fontSize: '1.1rem', mb: 1 }}>
                    {b.benefit_name}
                  </Typography>
                  <Typography variant="subtitle1" sx={{ fontWeight: 800, color: '#059669', fontSize: '1.2rem', mb: 1 }}>
                    {b.amount_or_percentage}
                  </Typography>
                  {b.conditions && (
                    <Typography variant="body2" sx={{ color: '#334155', fontSize: '0.86rem', mb: 1 }}>
                      <strong>Condition:</strong> {b.conditions}
                    </Typography>
                  )}
                  {b.source_clause && (
                    <Typography variant="caption" sx={{ color: '#1E40AF', display: 'block', fontSize: '0.78rem', fontWeight: 600 }}>
                      Clause Citation: {b.source_clause}
                    </Typography>
                  )}
                </Paper>
              </Grid>
            ))}
          </Grid>
        </Card>
      </Box>

      {/* ─── SECTION 4: DOCUMENTS REQUIRED (CHECKLIST) ─── */}
      <Box id="documents" sx={{ mb: 4, scrollMarginTop: 130 }}>
        <Card sx={{ bgcolor: '#FFFFFF', border: '1px solid #CBD5E1', borderRadius: '14px', p: 3.5, boxShadow: '0 2px 8px rgba(15, 23, 42, 0.04)' }}>
          <Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" alignItems="center" sx={{ mb: 2 }}>
            <Stack direction="row" alignItems="center" spacing={1.5}>
              <Box
                sx={{
                  width: 36,
                  height: 36,
                  borderRadius: '8px',
                  bgcolor: '#EFF6FF',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                }}
              >
                <AssignmentTurnedInIcon sx={{ color: '#1E40AF', fontSize: 22 }} />
              </Box>
              <Typography variant="h5" sx={{ fontWeight: 800, color: '#0F2E59', fontSize: '1.3rem' }}>
                4. Mandatory Statutory Documents Required ({requiredDocs.length})
              </Typography>
            </Stack>

            <Button
              size="small"
              variant="outlined"
              onClick={handleExportChecklist}
              startIcon={<FileDownloadOutlinedIcon />}
              sx={{
                borderColor: '#0F2E59',
                color: '#0F2E59',
                fontWeight: 700,
                fontSize: '0.82rem',
                textTransform: 'none',
                mt: { xs: 1.5, sm: 0 },
                '&:hover': { bgcolor: '#F1F5F9' },
              }}
            >
              Download Checklist (.txt)
            </Button>
          </Stack>

          <Typography variant="body2" sx={{ color: '#475569', fontSize: '0.92rem', mb: 2.5 }}>
            Check off the documents your business already possesses to verify your statutory filing readiness before approaching DIC officers or banks.
          </Typography>

          <Stack spacing={1.5}>
            {requiredDocs.map((doc: any, index: number) => {
              const isChecked = Boolean(checkedDocs[doc.id])
              return (
                <Paper
                  key={doc.id}
                  onClick={() => toggleDoc(doc.id)}
                  elevation={0}
                  sx={{
                    p: 2,
                    bgcolor: isChecked ? '#ECFDF5' : '#F8FAFC',
                    border: `1px solid ${isChecked ? '#34D399' : '#E2E8F0'}`,
                    borderRadius: '10px',
                    cursor: 'pointer',
                    transition: 'all 0.15s ease',
                    '&:hover': {
                      borderColor: '#0F2E59',
                      bgcolor: isChecked ? '#ECFDF5' : '#F1F5F9',
                    },
                  }}
                >
                  <Stack direction="row" spacing={1.75} alignItems="flex-start">
                    <Checkbox
                      checked={isChecked}
                      onChange={() => toggleDoc(doc.id)}
                      sx={{
                        p: 0.25,
                        color: '#94A3B8',
                        '&.Mui-checked': { color: '#059669' },
                      }}
                    />
                    <Box sx={{ flex: 1 }}>
                      <Stack direction="row" alignItems="center" spacing={1} flexWrap="wrap" sx={{ mb: 0.5 }}>
                        <Typography
                          variant="subtitle2"
                          sx={{
                            fontWeight: 800,
                            color: isChecked ? '#065F46' : '#0F2E59',
                            fontSize: '0.95rem',
                          }}
                        >
                          {index + 1}. {doc.name}
                        </Typography>
                        <Chip
                          label={doc.category}
                          size="small"
                          sx={{
                            bgcolor: '#EFF6FF',
                            color: '#1E40AF',
                            fontSize: '0.7rem',
                            height: 22,
                            fontWeight: 700,
                          }}
                        />
                        {doc.mandatory && (
                          <Chip
                            label="MANDATORY"
                            size="small"
                            sx={{
                              bgcolor: '#FEF2F2',
                              color: '#991B1B',
                              border: '1px solid #FECACA',
                              fontSize: '0.65rem',
                              height: 20,
                              fontWeight: 800,
                            }}
                          />
                        )}
                      </Stack>
                      <Typography variant="body2" sx={{ color: '#475569', fontSize: '0.86rem', lineHeight: 1.5 }}>
                        {doc.desc}
                      </Typography>
                    </Box>
                  </Stack>
                </Paper>
              )
            })}
          </Stack>
        </Card>
      </Box>

      {/* ─── SECTION 5: STEP-BY-STEP APPLICATION PROCEDURE ─── */}
      <Box id="procedure" sx={{ mb: 4, scrollMarginTop: 130 }}>
        <Card sx={{ bgcolor: '#FFFFFF', border: '1px solid #CBD5E1', borderRadius: '14px', p: 3.5, boxShadow: '0 2px 8px rgba(15, 23, 42, 0.04)' }}>
          <Stack direction="row" alignItems="center" spacing={1.5} sx={{ mb: 2 }}>
            <Box
              sx={{
                width: 36,
                height: 36,
                borderRadius: '8px',
                bgcolor: '#FFFBEB',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
              }}
            >
              <DomainOutlinedIcon sx={{ color: '#D97706', fontSize: 22 }} />
            </Box>
            <Typography variant="h5" sx={{ fontWeight: 800, color: '#0F2E59', fontSize: '1.3rem' }}>
              5. How to Apply? (Sequential Application Procedure)
            </Typography>
          </Stack>

          <Typography variant="body2" sx={{ color: '#475569', mb: 3, fontSize: '0.92rem' }}>
            Follow the sequential statutory roadmap extracted verbatim from official operational guidelines:
          </Typography>

          <Stack spacing={2}>
            {(scheme.application_steps || [
              'Verify MSME Udyam Registration & Bank Account validity.',
              'Compile statutory DPR and CA Chartered Accountant verification certificates.',
              'Submit online declaration or registration form on the official government portal.',
              'Submit dossier to District Industries Centre (DIC) / Member Lending Institution (MLI) for appraisal.',
              'Receive sanction approval and Direct Benefit Transfer (DBT) grant subsidy disbursement.',
            ]).map((step: string, index: number) => (
              <Box
                key={index}
                sx={{
                  display: 'flex',
                  alignItems: 'flex-start',
                  gap: 2,
                  p: 2,
                  borderRadius: '10px',
                  bgcolor: '#F8FAFC',
                  border: '1px solid #E2E8F0',
                }}
              >
                <Box
                  sx={{
                    width: 32,
                    height: 32,
                    borderRadius: '8px',
                    bgcolor: '#0F2E59',
                    color: '#FFFFFF',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    fontWeight: 800,
                    fontSize: '0.85rem',
                    flexShrink: 0,
                  }}
                >
                  {index + 1}
                </Box>
                <Typography variant="body2" sx={{ color: '#1E293B', fontSize: '0.92rem', lineHeight: 1.6, pt: 0.3 }}>
                  {step}
                </Typography>
              </Box>
            ))}
          </Stack>

          {scheme.official_portal_url && (
            <Box sx={{ mt: 3, pt: 2, borderTop: '1px solid #E2E8F0' }}>
              <Button
                variant="contained"
                component="a"
                href={scheme.official_portal_url}
                target="_blank"
                rel="noreferrer"
                endIcon={<OpenInNewIcon sx={{ fontSize: 16 }} />}
                sx={{
                  bgcolor: '#0F2E59',
                  color: '#FFFFFF',
                  fontWeight: 700,
                  textTransform: 'none',
                  px: 3,
                  py: 1,
                  borderRadius: '8px',
                  boxShadow: '0 3px 10px rgba(15, 46, 89, 0.25)',
                  '&:hover': { bgcolor: '#0A1E3A' },
                }}
              >
                Proceed to Official Application Portal
              </Button>
            </Box>
          )}
        </Card>
      </Box>

      {/* ─── SECTION 6: STATUTORY GAZETTE CITATIONS & LEGAL REFERENCE ─── */}
      <Box id="gazette" sx={{ mb: 4, scrollMarginTop: 130 }}>
        <Card sx={{ bgcolor: '#FFFFFF', border: '1px solid #CBD5E1', borderRadius: '14px', p: 3.5, boxShadow: '0 2px 8px rgba(15, 23, 42, 0.04)' }}>
          <Stack direction="row" alignItems="center" spacing={1.5} sx={{ mb: 2 }}>
            <Box
              sx={{
                width: 36,
                height: 36,
                borderRadius: '8px',
                bgcolor: '#FAF5FF',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
              }}
            >
              <GavelOutlinedIcon sx={{ color: '#7C3AED', fontSize: 22 }} />
            </Box>
            <Typography variant="h5" sx={{ fontWeight: 800, color: '#0F2E59', fontSize: '1.3rem' }}>
              6. Official Gazette & Statutory Legal Verification Reference
            </Typography>
          </Stack>

          <Paper
            elevation={0}
            sx={{
              p: 2.5,
              bgcolor: '#F8FAFC',
              border: '1px solid #CBD5E1',
              borderRadius: '10px',
              mb: 2,
            }}
          >
            <Typography variant="subtitle2" sx={{ color: '#7C3AED', fontWeight: 800, mb: 1 }}>
              Official Legal Gazette / Government Resolution:
            </Typography>
            <Typography variant="body1" sx={{ color: '#0F2E59', fontWeight: 700, fontSize: '0.98rem', mb: 1 }}>
              {scheme.gazette_notification || 'Published in the Gazette of India & Official State Notifications'}
            </Typography>
            <Typography variant="caption" sx={{ color: '#475569', display: 'block', fontSize: '0.84rem' }}>
              Issuing Authority: {scheme.ministry} • Nodal Implementing Body: {scheme.implementing_agency || 'Directorate of MSME'}
            </Typography>
          </Paper>

          <Typography variant="caption" sx={{ color: '#64748B', display: 'block', lineHeight: 1.6 }}>
            * Statutory Disclaimer: All data points, slabs, and document prerequisites reflect published government guidelines. Scheme sanctions and subsidy disbursements remain subject to official appraisal by respective DIC officers, SIDBI, CGTMSE, or lending institutions.
          </Typography>
        </Card>
      </Box>
    </Box>
  )
}

export default SchemeDetailPage
