# Generated by Django 4.2.13 on 2026-09-30 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('udyam_certificate', 'Udyam Registration Certificate'), ('gstin_certificate', 'GSTIN Registration Certificate'), ('pan_card', 'Enterprise / Promoter PAN Card'), ('balance_sheet', 'Audited Balance Sheet & P&L'), ('bank_statement', '6-Month Operational Bank Statement'), ('caste_certificate', 'SC / ST / OBC Caste Certificate'), ('land_rent_deed', 'Factory Land Deed or Registered Rent Agreement'), ('ca_certificate', 'Chartered Accountant Investment & Turnover Certificate'), ('machinery_quotation_invoice', 'Machinery Quotation / Commercial Invoice'), ('zed_certificate', 'ZED Bronze / Silver / Gold Certificate'), ('other', 'Other Supporting Official Document')], max_length=40)),
                ('title', models.CharField(help_text='Display name or file title', max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/')),
                ('file_hash', models.CharField(blank=True, help_text='SHA-256 checksum ensuring document tamper-proofing', max_length=64)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified — Pending Review'), ('processing', 'Processing OCR & Fact Extraction'), ('verified', 'Verified — Authenticated by Document Service'), ('rejected', 'Rejected — Discrepancy Found'), ('expired', 'Expired — Document Past Validity Date')], default='unverified', max_length=20)),
                ('extracted_facts', models.JSONField(blank=True, default=dict, help_text='Extracted key facts (e.g. udyam_number, turnover, investment, caste)')),
                ('page_count', models.IntegerField(default=1)),
                ('extraction_method', models.CharField(choices=[('native_pdf', 'Native PDF Text Extraction'), ('paddle_ocr', 'PaddleOCR / Image OCR'), ('regex_heuristic', 'Regex / Structured Heuristic'), ('manual', 'Manual Entry')], default='native_pdf', max_length=30)),
                ('raw_extracted_text', models.TextField(blank=True, help_text='Extracted raw text for debugging and audit')),
                ('document_issue_date', models.DateField(blank=True, help_text='Date of issue / generation printed on document', null=True)),
                ('document_period', models.CharField(blank=True, help_text='e.g. FY 2023-24, Q3 2024-25', max_length=50)),
                ('rejection_reason', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(help_text='Enterprise associated with this document', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='business_profiles.businessprofile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'business_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentFactProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fact_key', models.CharField(help_text='e.g. udyam_registration_number, annual_turnover_lakhs, investment_in_plant_machinery_lakhs', max_length=100)),
                ('current_value', models.JSONField(blank=True, help_text='Current profile / self-declared value', null=True)),
                ('extracted_value', models.JSONField(help_text='Value parsed from official document')),
                ('source_page', models.IntegerField(default=1, help_text='Page number in source document where fact was detected')),
                ('evidence_snippet', models.TextField(blank=True, help_text='Exact string or clause excerpt from document')),
                ('confidence_score', models.FloatField(default=1.0, help_text='0.0 to 1.0 confidence of OCR / extraction')),
                ('has_conflict', models.BooleanField(default=False, help_text='True if extracted value contradicts current profile value')),
                ('conflict_notes', models.TextField(blank=True, help_text='Explanation of conflict or divergence')),
                ('status', models.CharField(choices=[('pending_review', 'Pending User Review'), ('accepted', 'Accepted by User — Applied to Profile'), ('rejected', 'Rejected by User — Retained Self-Declared Value'), ('conflict_reported', 'Conflict Reported — Discrepancy Noted')], default='pending_review', max_length=30)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_fact_proposals', to='business_profiles.businessprofile')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact_proposals', to='documents.businessdocument')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_fact_proposals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_title', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('uploaded', 'Document Uploaded'), ('hash_verified', 'Cryptographic Hash Verified'), ('facts_extracted', 'Facts Extracted via OCR/Parser'), ('proposals_generated', 'Fact Proposals Generated for User Review'), ('proposal_accepted', 'Proposal Accepted by User'), ('proposal_rejected', 'Proposal Rejected by User'), ('status_changed', 'Verification Status Changed'), ('deleted', 'Document Deleted per Retention Policy')], max_length=30)),
                ('details', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='documents.businessdocument')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CrossDocumentConsistencyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consistency_matrix', models.JSONField(default=dict, help_text='Detailed comparison per attribute across Profile, Udyam, GST, Financials, Quotation')),
                ('total_checks', models.IntegerField(default=0)),
                ('matches_count', models.IntegerField(default=0)),
                ('conflicts_count', models.IntegerField(default=0)),
                ('missing_count', models.IntegerField(default=0)),
                ('outdated_count', models.IntegerField(default=0)),
                ('unknown_count', models.IntegerField(default=0)),
                ('overall_status', models.CharField(choices=[('clean_match', 'All Active Facts Consistent'), ('conflicts_detected', 'Conflicts Detected — User Review Required'), ('missing_evidence', 'Missing Documentary Evidence'), ('outdated_documents', 'Outdated Documents Detected')], default='clean_match', max_length=30)),
                ('summary_notes', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consistency_reports', to='business_profiles.businessprofile')),
            ],
            options={
                'db_table': 'cross_document_consistency_reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='businessdocument',
            index=models.Index(fields=['business_profile', 'document_type'], name='business_do_busines_194a2e_idx'),
        ),
        migrations.AddIndex(
            model_name='businessdocument',
            index=models.Index(fields=['verification_status'], name='business_do_verific_c15a3e_idx'),
        ),
    ]
