# Generated by Django 4.2.13 on 2026-10-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdocument',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified - Pending Review'), ('processing', 'Processing OCR & Fact Extraction'), ('verified', 'Verified - Authenticated by Document Service'), ('rejected', 'Rejected - Discrepancy Found'), ('expired', 'Expired - Document Past Validity Date')], default='unverified', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentfactproposal',
            name='status',
            field=models.CharField(choices=[('pending_review', 'Pending User Review'), ('accepted', 'Accepted by User - Applied to Profile'), ('rejected', 'Rejected by User - Retained Self-Declared Value'), ('conflict_reported', 'Conflict Reported - Discrepancy Noted')], default='pending_review', max_length=30),
        ),
    ]
