# Generated by Django 4.2.13 on 2026-09-30 10:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_profiles', '0001_initial'),
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('narrative', models.TextField(blank=True)),
                ('total_opportunities', models.IntegerField(default=0)),
                ('matched_count', models.IntegerField(default=0)),
                ('potential_count', models.IntegerField(default=0)),
                ('scheme_results', models.JSONField(default=list)),
                ('relationships', models.JSONField(default=list)),
                ('action_plan', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='business_profiles.businessprofile')),
                ('goal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='strategy', to='business_profiles.businessgoal')),
            ],
            options={
                'db_table': 'strategies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategyItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=40)),
                ('score', models.FloatField(default=0.0)),
                ('priority', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3)),
                ('is_recommended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_items', to='policies.scheme')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='strategy.strategy')),
            ],
            options={
                'db_table': 'strategy_items',
                'ordering': ['priority', '-score'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(max_length=40)),
                ('edge_label', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='policies.scheme')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph_edges', to='strategy.strategy')),
                ('target_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='policies.scheme')),
            ],
            options={
                'db_table': 'opportunity_edges',
            },
        ),
        migrations.CreateModel(
            name='EvidenceGraphNode',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('node_type', models.CharField(choices=[('Business', 'Business'), ('BusinessFact', 'Business Fact'), ('Goal', 'Goal'), ('Rule', 'Rule'), ('Scheme', 'Scheme'), ('SchemeVersion', 'Scheme Version'), ('Evidence', 'Evidence'), ('Relationship', 'Relationship'), ('Prerequisite', 'Prerequisite'), ('Blocker', 'Blocker'), ('UnlockAction', 'Unlock Action'), ('Action', 'Action')], max_length=50)),
                ('label', models.CharField(max_length=500)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_nodes', to='strategy.strategy')),
            ],
            options={
                'db_table': 'evidence_graph_nodes',
            },
        ),
        migrations.CreateModel(
            name='EvidenceGraphEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('edge_type', models.CharField(choices=[('HAS_FACT', 'HAS_FACT'), ('TARGETS_GOAL', 'TARGETS_GOAL'), ('EVALUATED_BY', 'EVALUATED_BY'), ('SATISFIES', 'SATISFIES'), ('FAILS', 'FAILS'), ('UNKNOWN_FOR', 'UNKNOWN_FOR'), ('SUPPORTED_BY', 'SUPPORTED_BY'), ('REQUIRES', 'REQUIRES'), ('RELATES_TO', 'RELATES_TO'), ('BLOCKS', 'BLOCKS'), ('MAY_UNLOCK', 'MAY_UNLOCK'), ('LEADS_TO', 'LEADS_TO')], max_length=50)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='strategy.evidencegraphnode')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_edges', to='strategy.strategy')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='strategy.evidencegraphnode')),
            ],
            options={
                'db_table': 'evidence_graph_edges',
            },
        ),
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Targeted Execution Plan', max_length=255)),
                ('total_steps', models.PositiveIntegerField(default=0)),
                ('estimated_total_weeks', models.PositiveIntegerField(default=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('strategy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='strategy.strategy')),
            ],
            options={
                'db_table': 'action_plans',
            },
        ),
        migrations.AddIndex(
            model_name='evidencegraphnode',
            index=models.Index(fields=['node_type'], name='evidence_gr_node_ty_bfabae_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencegraphnode',
            index=models.Index(fields=['strategy'], name='evidence_gr_strateg_c7b4cb_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencegraphedge',
            index=models.Index(fields=['edge_type'], name='evidence_gr_edge_ty_81469e_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencegraphedge',
            index=models.Index(fields=['source', 'target'], name='evidence_gr_source__a0a396_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencegraphedge',
            index=models.Index(fields=['strategy'], name='evidence_gr_strateg_5a0f3b_idx'),
        ),
    ]
