# Generated by Django 4.2.13 on 2026-09-30 10:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policies', '0001_initial'),
        ('business_profiles', '0001_initial'),
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationPreparationWorkspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_preparation', 'In Preparation'), ('ready_for_portal', 'Ready to Continue to Portal'), ('applied_external', 'Applied on Official Portal'), ('archived', 'Archived')], default='in_preparation', max_length=30)),
                ('official_portal_url', models.URLField(help_text='e.g. https://ifp.gujarat.gov.in or https://cgtmse.in', max_length=500)),
                ('official_portal_name', models.CharField(help_text='e.g. Gujarat Investor Facilitation Portal (IFP)', max_length=150)),
                ('application_mode', models.CharField(default='Online Single Window Portal', max_length=50)),
                ('disclaimer_notice', models.TextField(default='UdyamNiti prepares your documentation and eligibility facts. In accordance with government regulations, final submission, OTP/Aadhaar verification, and legal declarations must be executed directly by the authorized applicant on the official government portal.')),
                ('workspace_data', models.JSONField(default=dict)),
                ('documents_ready_count', models.IntegerField(default=0)),
                ('documents_total_count', models.IntegerField(default=0)),
                ('info_ready_count', models.IntegerField(default=0)),
                ('info_total_count', models.IntegerField(default=0)),
                ('tasks_completed_count', models.IntegerField(default=0)),
                ('tasks_total_count', models.IntegerField(default=0)),
                ('unknowns_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_workspaces', to='business_profiles.businessprofile')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_workspaces', to='policies.scheme')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_workspaces', to='strategy.strategy')),
            ],
            options={
                'db_table': 'application_workspaces',
                'ordering': ['-updated_at'],
                'unique_together': {('business_profile', 'scheme')},
            },
        ),
        migrations.CreateModel(
            name='ActionTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.IntegerField(default=1, help_text='Execution order (1 is top priority)')),
                ('title', models.CharField(help_text='Actionable task headline', max_length=300)),
                ('rationale', models.TextField(help_text='Why this task is required for statutory progress')),
                ('description', models.TextField(blank=True, help_text='Detailed procedural step-by-step instructions')),
                ('category', models.CharField(choices=[('verification', 'Verify Scheme Condition / Fact'), ('prerequisite', 'Prerequisite — Must Complete First'), ('documentation', 'Prepare Documentation / Project Report'), ('certification', 'Investigate / Attain Certification'), ('relationship_review', 'Review Relationship & Stacking Evidence'), ('portal_submission', 'Visit Official Application Portal'), ('compliance', 'Statutory Compliance')], default='portal_submission', max_length=40)),
                ('dependency_ids', models.JSONField(blank=True, default=list, help_text='List of task UUIDs that must be completed before this task can start')),
                ('related_scheme_ids', models.JSONField(blank=True, default=list, help_text='List of scheme codes related to this action')),
                ('evidence_ids', models.JSONField(blank=True, default=list, help_text='Statutory chunk IDs or Gazette clause references justifying this step')),
                ('external_url', models.URLField(blank=True, help_text='Direct link to official government portal (e.g. udyamregistration.gov.in, ifp.gujarat.gov.in)', null=True)),
                ('portal_label', models.CharField(blank=True, help_text='e.g. Gujarat IFP Portal', max_length=100)),
                ('requires_user_action', models.BooleanField(default=True, help_text='Always True: UdyamNiti does not automatically submit applications without explicit user action')),
                ('official_deadline', models.CharField(blank=True, help_text="Official statutory deadline if specified in Gazette (e.g. 'Within 1 year from DOCP')", max_length=200)),
                ('estimated_time', models.CharField(default='1-2 days', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('portal_url', models.URLField(blank=True, null=True)),
                ('blocker_for', models.JSONField(blank=True, default=list)),
                ('unlocks_scheme_code', models.CharField(blank=True, max_length=50)),
                ('potential_benefit_lakhs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_tasks', to='business_profiles.businessprofile')),
                ('scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_tasks', to='policies.scheme')),
                ('strategy', models.ForeignKey(help_text='Strategy plan this action belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='strategy.strategy')),
            ],
            options={
                'db_table': 'action_tasks',
                'ordering': ['priority', 'created_at'],
                'indexes': [models.Index(fields=['strategy', 'status'], name='action_task_strateg_637cb2_idx'), models.Index(fields=['business_profile', 'priority'], name='action_task_busines_d468ed_idx')],
            },
        ),
    ]
