# Generated by Django 4.2.13 on 2026-09-30 10:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policies', '0001_initial'),
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityUnlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unlock_action', models.CharField(help_text='Actionable title of unlock candidate', max_length=300)),
                ('current_blocker', models.TextField(help_text='The missing condition or barrier causing non-match or uncertainty')),
                ('affected_opportunities', models.JSONField(blank=True, default=list, help_text='List of schemes that become relevant/eligible once this unlock is completed')),
                ('evidence_ids', models.JSONField(blank=True, default=list, help_text='Statutory chunk/document IDs supporting this unlock mechanism')),
                ('required_user_confirmation', models.TextField(help_text='What proof or user confirmation is required to verify resolution')),
                ('explanation', models.TextField(help_text='Explanation of the causal unlock path without false promises')),
                ('prerequisite_type', models.CharField(choices=[('registration', 'Statutory / Regulatory Registration'), ('certification', 'Quality / Sustainability Certification'), ('documentation', 'Sanction Letter / CA Certificate'), ('prerequisite_scheme', 'Prerequisite Scheme Milestone'), ('verification', 'Profile Fact Clarification')], default='documentation', max_length=40)),
                ('is_resolvable', models.BooleanField(default=True)),
                ('potential_benefit_lakhs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('difficulty', models.CharField(choices=[('low', 'Low Effort (Self-declaration or portal filing)'), ('medium', 'Medium Effort (Document or certification upload)'), ('high', 'High Effort (Audit, inspection, or banking sanction)')], default='medium', max_length=20)),
                ('estimated_days', models.IntegerField(default=7)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('missing_fact_key', models.CharField(blank=True, max_length=100)),
                ('action_required', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unlock_recommendations', to='policies.scheme')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='strategy.strategy')),
            ],
            options={
                'db_table': 'opportunity_unlocks',
                'ordering': ['-potential_benefit_lakhs', 'created_at'],
            },
        ),
    ]
