# Generated by Django 4.2.13 on 2026-09-30 10:18

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.vector
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('completed', 'Completed Successfully'), ('partial_quarantine', 'Completed with Quarantined Documents'), ('failed', 'Batch Failed')], default='completed', max_length=25)),
                ('total_sources', models.PositiveIntegerField(default=0)),
                ('processed_sources', models.PositiveIntegerField(default=0)),
                ('quarantined_sources', models.PositiveIntegerField(default=0)),
                ('total_chunks_created', models.PositiveIntegerField(default=0)),
                ('duplicates_detected', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('error_log', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rag_ingestion_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicySourceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Full official title of the policy document', max_length=350)),
                ('authority', models.CharField(help_text='Issuing ministry or department e.g. Ministry of MSME', max_length=255)),
                ('source_url', models.URLField(help_text='Direct canonical download URL', max_length=500)),
                ('source_tier', models.CharField(choices=[('tier_1_gazette', 'Tier 1: Gazette Notification'), ('tier_2_operational_guidelines', 'Tier 2: Operational Guidelines'), ('tier_3_ministry_circular', 'Tier 3: Ministry Circular / OM'), ('tier_4_portal_faq', 'Tier 4: Portal FAQ / Manual')], default='tier_2_operational_guidelines', max_length=35)),
                ('document_type', models.CharField(choices=[('pdf', 'Portable Document Format (PDF)'), ('html', 'Official Web Page / Portal HTML'), ('notification', 'Statutory Notification'), ('circular', 'Executive Circular'), ('resolution', 'Government Resolution (G.R.)'), ('faq', 'Public FAQ')], default='pdf', max_length=20)),
                ('notification_number', models.CharField(blank=True, max_length=150)),
                ('file', models.FileField(blank=True, null=True, upload_to='policy_documents/%Y/%m/')),
                ('file_hash', models.CharField(db_index=True, help_text='SHA-256 checksum for exact deduplication', max_length=64)),
                ('content_simhash', models.CharField(blank=True, help_text='SimHash for near-duplicate text detection', max_length=64)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('effective_date', models.DateField(help_text='Statutory date this document came into force')),
                ('effective_until', models.DateField(blank=True, help_text='Sunset or superseded date', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Ingestion'), ('processing', 'Processing & Chunking'), ('published', 'Published & Active in Vector Store'), ('quarantined', 'Quarantined (Parsing/Validation Failure)'), ('superseded', 'Superseded by Newer Policy Version')], db_index=True, default='pending', max_length=20)),
                ('quarantine_reason', models.TextField(blank=True, help_text='Error details if parsing or validation fails')),
                ('total_pages', models.PositiveIntegerField(default=1)),
                ('total_chunks', models.PositiveIntegerField(default=0)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheme', models.ForeignKey(blank=True, help_text='Associated scheme if known at ingestion time', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_documents', to='policies.scheme')),
            ],
            options={
                'db_table': 'rag_policy_source_documents',
                'ordering': ['-effective_date', '-ingested_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyDocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('authority', models.CharField(max_length=255)),
                ('source_url', models.URLField(max_length=500)),
                ('source_tier', models.CharField(max_length=35)),
                ('document_title', models.CharField(max_length=350)),
                ('publication_effective_date', models.DateField()),
                ('policy_version', models.PositiveIntegerField(default=1)),
                ('page_number', models.PositiveIntegerField(help_text='PDF page number where chunk occurs')),
                ('section_heading', models.CharField(blank=True, help_text='e.g. Clause 4.2: Eligible Investment', max_length=255)),
                ('chunk_index', models.PositiveIntegerField()),
                ('chunk_text', models.TextField()),
                ('chunk_hash', models.CharField(help_text='SHA-256 hash of the chunk text', max_length=64)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='rag.policysourcedocument')),
                ('scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_chunks', to='policies.scheme')),
            ],
            options={
                'db_table': 'rag_policy_document_chunks',
                'ordering': ['document', 'chunk_index'],
            },
        ),
        migrations.AddIndex(
            model_name='policysourcedocument',
            index=models.Index(fields=['file_hash'], name='rag_policy__file_ha_0d5849_idx'),
        ),
        migrations.AddIndex(
            model_name='policysourcedocument',
            index=models.Index(fields=['status', 'source_tier'], name='rag_policy__status_b789d6_idx'),
        ),
        migrations.AddIndex(
            model_name='policysourcedocument',
            index=models.Index(fields=['authority', 'effective_date'], name='rag_policy__authori_71826f_idx'),
        ),
        migrations.AddIndex(
            model_name='policydocumentchunk',
            index=models.Index(fields=['document', 'chunk_index'], name='rag_policy__documen_b48436_idx'),
        ),
        migrations.AddIndex(
            model_name='policydocumentchunk',
            index=models.Index(fields=['is_active', 'source_tier'], name='rag_policy__is_acti_e6c9fb_idx'),
        ),
        migrations.AddIndex(
            model_name='policydocumentchunk',
            index=models.Index(fields=['chunk_hash'], name='rag_policy__chunk_h_518074_idx'),
        ),
    ]
